crates/native_blockifier/src/py_transaction.rs, crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
Python [#32536](https://reviewable.io/reviews/starkware-industries/starkware/32536)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1110)
=> Change ` validate ` method of ` PyValidator ` to return the actual cost (as opposed to the actual fee that was previously returned).

Cargo.lock, Cargo.toml, crates/native_blockifier/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1116)
=> Release 0.4.0-rc5 - internal

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1098)
=> Refactor, no business logic changes

crates/blockifier/src/execution/common_hints.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1125)
=> Add `ExecutionMode` and partial usages.

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1127)
=> Add `ExecuteMode` usage.

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1130)
=> Elin/merge main v0.12.3 into main

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1060)
=> Add pre-validation fee checks.

crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/native_blockifier/src/py_declare.rs, crates/native_blockifier/src/py_deploy_account.rs, crates/native_blockifier/src/py_invoke_function.rs, crates/native_blockifier/src/py_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1120)
=> Use try_from to catch errors in resources dict

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1131)
=> Fix conflict

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1132)
=> Revert `replace_class` block in validate mode.

crates/blockifier/src/fee/actual_cost.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1135)
=> create ` check_actual_cost_within_bounds ` .

crates/native_blockifier/src/py_transaction.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1134)
=> Unify the gateway validations to all transactions' types.

crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1111)
=> Add post_validate method.

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/strk_gas_price/gas_price.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_utils.rs, crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1061)
=> Perform pre-validation checks in PyValidator.

crates/native_blockifier/src/py_block_executor.rs
Block id is a StarkFelt, and can be larger than u64.
Python: https://reviewable.io/reviews/starkware-industries/starkware/32612
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1138)
=> Fix `block_id_at_target` return value bug

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/errors.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1140)
=> Refactor in prep for post-validation usage

crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1143)
=> Parametrize test

crates/blockifier/src/execution/entry_point_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1146)
=> Compute PC locations for stack trace test

crates/blockifier/src/fee/os_resources.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1142)
=> Update os resources file.'

crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1101)
=> Verify can pay 'max fee' for v3

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1150)
=> Bump blockifier to rc7

crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1151)
=> Move skip validate check to before the pre validations.

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1152)
=> Bump version to rc8

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1049)
=> Test resource overdraft

crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1165)
=> Move utils from test to test utils module

crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1166)
=> Add pre-validation cartesian tests

crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1167)
=> Add mid-validation cartesian test

crates/blockifier/src/block_execution_test.rs, crates/blockifier/src/execution/contract_address_test.rs, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/fee/strk_gas_price/gas_price_test.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/cached_state.rs, crates/blockifier/src/test_utils/dict_state_reader.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/bench/blockifier_bench.rs, crates/native_blockifier/src/py_test_utils.rs
and `CachedState` constructors
commit-id:dc18fb72
---
**Stack**:
- #1179
- #1178
- #1177
- #1176
- #1175 ⬅
=> Break up test_utils.rs: extract `DictStateReader`

crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1168)
=> Add mid-execution cartesian tests

Cargo.lock, Cargo.toml
Python: https://github.com/starkware-industries/starkware/pull/32792
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1190)
=> Release 0.4.0-rc9.2: secp resources fix

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1193)
=> Test fail to DeployAccount on undeclared class hash

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/struct_impls.rs
commit-id:d621942f
---
**Stack**:
- #1179
- #1178
- #1177
- #1176 ⬅
=> Break up test_utils.rs: extract struct extensions

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/invoke.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/bench/blockifier_bench.rs
commit-id:e0bf8ed2
---
**Stack**:
- #1179
- #1178
- #1177 ⬅
=> Break up test_utils.rs: invoke_args and friends

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/deploy_account.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/bench/blockifier_bench.rs
commit-id:67f489ab
---
**Stack**:
- #1179
- #1178 ⬅
=> Break up test_utils.rs: deploy account tx

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/declare.rs, crates/blockifier/src/test_utils/deploy_account.rs, crates/blockifier/src/test_utils/invoke.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1196)
=> Define and use DeclareTxArgs

crates/blockifier/src/test_utils/declare.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1197)
=> Reduce boilerplate by constructing AccountTransaction directly

crates/blockifier/src/test_utils/deploy_account.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1195)
=> Support V3 DeployAccount in tests

Cargo.lock, Cargo.toml
Python: https://reviewable.io/reviews/starkware-industries/starkware/32810#-
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1198)
=> merge main-v0.13.0 into main

crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1169)
=> Add post-execution cartesian tests

crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1171)
=> Make gas_and_fee depend on fee type

crates/blockifier/src/test_utils/invoke.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/native_blockifier/bench/blockifier_bench.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1202)
=> Remove redundant macro logic

crates/blockifier/src/test_utils/declare.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1200)
=> Support v3 declare (and others)

Cargo.lock, Cargo.toml, crates/native_blockifier/src/storage.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1204)
=> add enforce_file_exists to check on mdbx.dat file

crates/blockifier/feature_contracts/cairo0/account_with_long_validate.cairo, crates/blockifier/feature_contracts/cairo0/compiled/account_with_long_validate_compiled.json, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1213)
=> add test for deploy_account with constructor

crates/blockifier/Cargo.toml, crates/blockifier/README.md, crates/blockifier/src/abi/abi_utils.rs, crates/blockifier/src/abi/constants.rs, crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/os_usage.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/state_api.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transaction_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1216)
=> replace StarkNet with Starknet

crates/native_blockifier/src/py_transaction.rs, crates/native_blockifier/src/py_validator.rs
Python PR [#32886](https://reviewable.io/reviews/starkware-industries/starkware/32886)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1211)
=> Remove externalization of ` execute ` and ` validate ` of ` PyValidator ` .

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1224)
=> Add feature contracts module

crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1217)
=> Pass error info in #[source] variants

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/test_utils/initial_test_state.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1225)
=> Add test_utils::initial_test_state

crates/blockifier/src/test_utils/initial_test_state.rs, crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1229)
=> Update flavors test to new infra

crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1231)
=> Refactor test_validate_accounts_tx to use create test state util.

crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1227)
=> Use Cairo 1 account faulty in validate test.

crates/blockifier/src/execution/contract_address_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1239)
=> Update contract_address_test to new infra

Cargo.lock, Cargo.toml, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1241)
=> Elin/merge main v0.12.3 into main v0.13.0

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1238)
=> Update security tests to new infra

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1246)
=> add test for invalid transaction version

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1257)
=> Fix 0.3.0-rc3

crates/blockifier/Cargo.toml, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1234)
=> Split post-execution test

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1255)
=> add invoke_tx test with storage operation

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1263)
=> add to invoke_tx test xor and ec operations

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1266)
=> add signature operation to invoke_tx tests

crates/blockifier/src/transaction/post_execution_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1235)
=> Update post-execution test to new testing infra

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1260)
=> Update default_invoke_tx_args and usages to new infra

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1267)
=> add send_message operation to invoke_tx tests

crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1268)
=> Update test to new infra

crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1269)
=> Fix and update test_revert_invoke

crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1271)
=> Delete create_state, update create_test_init_data

crates/blockifier/src/block_context.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1182)
=> Use Fri instead of STRK when small unit is intended

crates/blockifier/src/test_utils/initial_test_state.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1283)
=> Refactor initial_test_state

crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/test_utils/contracts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1284)
=> Refactor test_get_execution_info

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1281)
=> Delete redundant util

crates/blockifier/src/test_utils/initial_test_state.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1277)
=> Fix logic of test_fail_deploy_account.

crates/native_blockifier/src/lib.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1286)
=> Adds PyBouncerInfo struct and uses it

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/state_api.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1233)
=> Collect the set of visited PCs in the block.

crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1289)
=> remove redundant dot at end of closing error msg

crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1250)
=> Split test_validate_accounts_tx to a test for constructor.

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1287)
=> Add get block hash scenario to constractor test.

crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1251)
=> Add invalid scenario to constructor test.

crates/blockifier/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1296)
=> Refactor more macros to share code.

crates/native_blockifier/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1293)
=> Organises errors alphabetically

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1300)
=> Add Patricia update estimation for Bouncer.

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/native_blockifier/src/lib.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1298)
=> Adds PyBouncerInfo struct and use it (#1286)

crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1302)
=> Add visited stoarge entries methods to execution objects.

crates/blockifier/src/state/cached_state.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1303)
=> Estimate Patricia update resources for Bouncer.

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_utils.rs
This gets the same job done but with less allocation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1108)
=> refacto: non_optional_call_infos return an iterator

crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1301)
=> Rename PyBouncerInfo field

crates/blockifier/src/transaction/transactions_test.rs
Refactor test_validate_accounts_tx to include all tx_types + constructor on deploy-account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1292)
=> Refactor test_validate_accounts_tx

crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_block_executor_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1311)
=> Elin/merge main v0.13.0 into main

crates/blockifier/src/execution/contract_class.rs, crates/native_blockifier/src/lib.rs, crates/native_blockifier/src/py_testing_wrappers.rs, crates/native_blockifier/src/py_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1314)
=> Add updated version of estimate_casm_hash_computation_resources().

crates/native_blockifier/src/py_state_diff.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1319)
=> Add use_kzg_da flag to PyBlockInfo.

crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1329)
=> Remove gas price bounds from general config

crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1337)
=> Small fix in into_block_context.

crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/bench/blockifier_bench.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1322)
=> Use try_from instead of as

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1320)
=> Refactor calculate_tx_gas_usage

crates/native_blockifier/src/lib.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1341)
=> Remove PyKzgResources. Reveal the state diff size.

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1352)
=> Revert changes of 776d7a52

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs
refactor(fee): split computation of tx l1 gas to sum of da and non-da
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1339)
=> refactor(fee): split computation of tx l1 gas to sum of da and non-da

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/os_usage.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transaction_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1361)
=> feat(fee): preparation-add the calldata length to the resource calculation

crates/blockifier/src/abi/constants.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1356)
=> build(fee): added new struct and field in preparation for using blob_gas

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
Changed the return type and function name of calculate_tx_l1_gas_usage(s)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1357)
=> feat(fee): modified calculate_tx_l1_gas_usage(s), added calculate_tx_gas_and_blob_gas_usage

crates/blockifier/src/abi/sierra_types.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1366)
=> style: remove some unnecessary variables

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
Moving PR over to main-v0.13.1.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1370)
=> feat(fee): modified calculate_tx_l1_gas_usage(s) added calculate_tx_gas_and_blob_gas_usage

crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1374)
=> feat(fee): check gas amount including discounted data gas

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/execution/entry_point_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1371)
=> test: add cairo0 variants to the new stack trace regression tests

crates/blockifier/src/execution/entry_point.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1378)
=> fix(execution): convert all local errors to stack trace

crates/blockifier/src/execution/syscalls/hint_processor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1373)
=> fix(execution): change additional as to from

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1388)
=> ci: ignore merge PRs when linting PR titles

.github/workflows/ci.yml, crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json, crates/blockifier/feature_contracts/cairo0/test_contract.cairo, crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1384)
=> Elin/merge main v0.13.1 into main

Cargo.lock, Cargo.toml, crates/blockifier/Cargo.toml, crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1397)
=> refactor: change CustomHint error usage into VirtualMachineError::Other(anyhow::Error)

crates/blockifier/src/state/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1398)
=> refactor(state): use get_nonce_updates

crates/blockifier/src/block_execution.rs, crates/blockifier/src/block_execution_test.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1386)
=> refactor: restructure old_block_number_and_hash as a struct

crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1401)
=> refactor: modified estimate_minimal_gas_vector for 4844

crates/blockifier/src/fee/fee_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1402)
=> refactor: modified extraction in extract_l1_blob_gas_usage (from unwrap_or(0) to expect)

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1404)
=> test: update test_call_contract to new infra

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1405)
=> test: update test_replace_class to new infra

crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1409)
=> chore(fee): use GasVector as a return type for gas computations

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/os_resources.rs, crates/blockifier/src/fee/os_usage.rs, crates/blockifier/src/fee/os_usage_test.rs, crates/blockifier/src/transaction/account_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1362)
=> feat(fee): adding a slope parameters to the os resources and use them

crates/blockifier/src/fee/os_usage.rs, crates/blockifier/src/transaction/transaction_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1411)
=> refactor(execution): split get_additional_os_resources

crates/blockifier/src/block.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_state_diff.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1391)
=> chore(execution): enforce nonzero gas prices

crates/blockifier/src/execution/entry_point.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1429)
=> chore(execution): saturate step bound on overflow

crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/fee/os_usage.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1412)
=> feat(execution): add the syscall resources to vm_resources

crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1428)
=> refactor(execution, native_blockifier): decouple BouncerInfo from Python

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1432)
=> refactor: add class_hash and storage_address into SyscallExecutionError::InnerCallExecutionError

crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1436)
=> test(execution): improve covrage of test_count_actual_storage_changes

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1417)
=> refactor(execution): the struct state changes and state changes count

crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1442)
=> fix(native_blockifier): fix unused imports

crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1441)
=> refactor(transaction): make DeclareTransaction fields public

crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1453)
=> refactor: remove enum VirtualMachineExecutionError

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/transaction/transactions.rs, crates/native_blockifier/src/py_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1434)
=> feat(fee): add ClassLengths struct to ActualCostBuilder

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1424)
=> refactor(execution): remove syscall_counter from ExecutionResources

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1459)
=> refactor(resources): Update syscall resources

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1465)
=> fix: os resources

crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1461)
=> feat(state): bouncer DA count: define StateWriteKeys

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1466)
=> chore: alphabetize top level keys in versioned constants

crates/blockifier/src/execution.rs, crates/blockifier/src/execution/bouncer.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1445)
=> refactor(execution, native_blockifier): move Bouncer to blockifier crate

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1426)
=> feat(fee): add gas cost for calldata bytes

crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/test_utils/prices.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/native_blockifier/src/lib.rs, crates/native_blockifier/src/py_testing_wrappers.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1447)
=> refactor(execution): delete enrty point ExecutionResources

crates/native_blockifier/src/transaction_executor.rs
Python PR [#33905](https://reviewable.io/reviews/starkware-industries/starkware/33905).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1470)
=> fix(transaction): set l1 hanlder payload size to None for non-l1 hanlder txs (bouncer count)

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1474)
=> feat(fee): charge for signatures per byte

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1477)
=> chore(execution): increase invoke_tx_max_n_steps

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1479)
=> chore(fee): update vm resource and l2 resource costs

Cargo.lock, Cargo.toml, crates/blockifier/Cargo.toml, crates/native_blockifier/src/py_testing_wrappers.rs, crates/native_blockifier/src/storage.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1460)
=> chore: upgrade papyrus version

Cargo.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1481)
=> fix: fix cargo.lock - remove cargo update

crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1484)
=> chore(fee): small fixes

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1493)
=> Release v0.5.0-rc.1

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1483)
=> fix: update the event limit constants

crates/blockifier/src/state/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1505)
=> refactor(state): remove unnecessary derive

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/test_utils/declare.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_transaction.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1480)
=> refactor(transaction): remove public fields, add new function

crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1485)
=> refactor(execution): type of additional_data in test_validate_accounts_tx

crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/syscalls/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1508)
=> refactor: use versioned_constants function when possible

crates/blockifier/feature_contracts/cairo0/account_faulty.cairo, crates/blockifier/feature_contracts/cairo0/compiled/account_faulty_compiled.json, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1512)
=> test(execution): get_block_number and get_block_timestamp in test_validate_accounts_tx for Cairo0

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1498)
=> chore(fee): update os resources to include 4844 calculations

crates/blockifier/src/lib.rs, crates/native_blockifier/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1527)
=> chore!: limit pointer width in both crates

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1517)
=> fix: update the tx event limit constants

Cargo.lock, Cargo.toml
Python: https://reviewable.io/reviews/starkware-industries/starkware/34044
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1540)
=> chore: release 0.5.0-rc.2: 13_0.json support

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1541)
=> fix: generate_starknet_os_resources python target fix

Cargo.lock, Cargo.toml, crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1545)
=> Merge main-v0.13.1 into main

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1547)
=> refactor: remove some magic numbers from tests

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1549)
=> fix!: update max_contract_bytecode_size to 81k

scripts/merge_branches.py, scripts/merge_status.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1543)
=> chore: add merge_status.py script

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1555)
=> ci: advance setup-python action version

crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1522)
=> chore: panic if u128_from_usize fails

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1558)
=> chore: release v0.5.0-rc.3

crates/blockifier/src/fee/gas_usage_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1471)
=> test(fee): test get_message_segment_length function

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/fee/fee_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1570)
=> fix: unwrap called on u128

crates/blockifier/src/blockifier/block_test.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/cached_state.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1556)
=> test: use FeatureContract in create_test_state and tests which uses it

Cargo.lock, Cargo.toml, crates/blockifier/src/blockifier/bouncer.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/native_blockifier/src/py_transaction_execution_info.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1571)
=> Dori/Merge main-v0.13.1 into main

crates/blockifier/src/fee/gas_usage_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1574)
=> chore: remove final f64s

Cargo.toml, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1575)
=> chore: remove some 'as' conversions and enforce no 'as' conversions

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1552)
=> test: use feature contract in test_l1_handler

crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1583)
=> chore: wrapper for serialized TransactionExecutionInfo

crates/blockifier/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1587)
=> test: improve readablity of util trivial_external_entry_point

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1533)
=> refactor(fee): merge TransactionExecutionInfo calculations for Bouncer

crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1559)
=> refactor: lift the order assumption on the os constants in versioned constants json

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1589)
=> test: remove deprecated_create_test_state util

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
Part 2 is a bit more complicated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1592)
=> test: remove deprecated_create_deploy_test_state util

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1561)
=> refactor: sort versioned_constants json

crates/blockifier/src/blockifier/bouncer.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/gas_usage.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1586)
=> fix(fee): separate Starknet gas usage from other types of l1 gas usage

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1580)
=> refactor: creating intermediate struct StarknetResources to hold the L2 resources for a transaction

crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/transaction/objects_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1560)
=> test(fee): transaction execution info summarize info for bouncer test

crates/native_blockifier/src/py_block_executor.rs
…ng execute function
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1579)
=> feat(native_blockifier): add naive implementation for execute_txs using execute function

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/versioned_constants.rs
python PR-
https://github.com/starkware-industries/starkware/pull/34155
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1590)
=> refactor: change l2_resource_cost to to be of type ResourceCost (Ratio)

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1585)
=> refactor: adding code_size field to StarknetResources

crates/blockifier/src/transaction/objects_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1565)
=> test(fee): add test to TransactionExecutionInfo n_events

crates/blockifier/src/execution/syscalls/syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1593)
=> test: remove create_deploy_test_state part 1

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1576)
=> feat(execution): compute bouncer weight of reverted tx explicitly

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1598)
=> refactor: added state_changes_count to StarknetResources

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1600)
=> test: remove the test util deprecated_create_deploy_test_state

crates/blockifier/src/blockifier/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1577)
=> feat(execution): pass correct bouncer info

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1604)
=> test: remove redandant use of test util

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/contracts.rs, crates/native_blockifier/src/state_readers/papyrus_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1605)
=> test: remove the test util trivial_external_entry_point

crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils.rs, crates/native_blockifier/src/py_block_executor_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1607)
=> test: remove test util get_test_contract_class

crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/test_utils/initial_test_state.rs, crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1608)
=> test: refactor number of allowed instances in feature contracts

crates/native_blockifier/bench/blockifier_bench.rs
I checked using `cargo bench`. There is an improvement of ~17%.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1609)
=> test: use feature contract in benchmarking

crates/blockifier/src/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1611)
=> test: remove old constants for class hashes and addresses

crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1613)
=> chore: utility methods for GasVector

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1500)
=> refactor(transaction): add v3 txes to versioned_constants

crates/blockifier/src/fee/actual_cost.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1619)
=> chore(fee): remove stale todo

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1624)
=> chore: release v0.5.0

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1567)
=> fix: make the test pass wthout using magic numbers

crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/fee/gas_usage_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1597)
=> refactor(execution): change CallInfo into_iter to iter

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1622)
=> fix(transaction): make l1 handler test pass without using magic numbers

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1610)
=> refactor: added L1<>L2 meesages related fields to StarknetResources

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1642)
=> refactor: change `get_message_gas_usage` input to be of type MessageL1CostInfo

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1614)
=> refactor: add recursive error stack handling

crates/blockifier/src/blockifier/bouncer.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1625)
=> test: create test for tx_executor

crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1646)
=> refactor: added events cost to StarknetResources

crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/transaction_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1653)
=> fix(native_blockifier): fix memory leak when passing bytes to Python

crates/blockifier/src/bouncer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1582)
=> refactor: bouncer - update used state entries sets

crates/blockifier/src/blockifier/transaction_executor_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1652)
=> refactor: test tx_executor on l1 handler

crates/blockifier/src/blockifier/transaction_executor_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1630)
=> test: add deploy account scenario to test_tx_executor

crates/blockifier/src/blockifier/transaction_executor_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1629)
=> test: add invoke test to tx_executor

crates/blockifier/src/blockifier/transaction_executor_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1626)
=> test: declare on tx_executor

crates/blockifier/src/execution/entry_point_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1662)
=> test: change stack trace tests to execute via an account contract

crates/blockifier/src/execution/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1665)
=> fix: cap error stack length at 10000 chars

crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1667)
=> refactor: remove VirtualMachineExecutionErrorWithTrace type

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1657)
=> chore: run feature tests in the ci

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1668)
=> fix: remove dedicated+temporary trace regression fix

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1672)
=> feat: add function selector into lib call and call contract errors

crates/blockifier/src/execution/errors.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1673)
=> refactor: add selector into selected TransactionExecutionError variants

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1670)
=> refactor: initial reformatting of stack trace using the new framework

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1681)
=> refactor: add class hash to CallContractExecutionError

crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/versioned_constants.rs
previous PR- https://github.com/starkware-libs/blockifier/pull/1654
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1676)
=> fix(fee): fixed previous PR, wrong parentheses

crates/blockifier/src/abi/constants.rs, crates/blockifier/src/blockifier/bouncer.rs, crates/blockifier/src/bouncer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1671)
=> refactor(execution): get_tx_weights for the bouncer

crates/blockifier/src/execution/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1689)
=> feat: better trimming of an error trace string

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1638)
=> fix: update version constant file for optimize-search-sorted

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1655)
=> refactor(fee): added TransactionResources struct

crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1685)
=> chore: move code size logic to ClassInfo

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/execution/contract_class.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/fee/gas_usage_test.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transaction_utils.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1687)
=> refactor: pass self by reference in count_for_fee_charge

crates/blockifier/src/context.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/fee_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1688)
=> chore: implement utility fee_token_address method

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transaction_execution.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1686)
=> refactor: construct ActualCost without a Builder pattern

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1697)
=> chore: rename struct and fields

crates/blockifier/src/concurrency.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1677)
=> feat: scheduler basics

crates/blockifier/src/versioned_constants.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_utils.rs, crates/native_blockifier/src/py_validator.rs
Small refactor towards #1678.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1710)
=> chore: refactor versioned_constants_with_overrides

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/fee_test.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1696)
=> refactor(fee): removed bouncer resources field from tx execution info

crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/syscalls/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1715)
=> fix: correct error type in validate mode when calling contract

crates/blockifier/src/bouncer.rs, crates/blockifier/src/fee/gas_usage.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1711)
=> chore: refactor messages gas computation for bouncer

crates/blockifier/src/concurrency/versioned_state_proxy_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1717)
=> fix(execution): join threads in versioned state proxy test

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1615)
=> refactor: fill os_constants in test_successful_parsing

crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1616)
=> refactor: fill os_constants in test_default_values

crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1617)
=> refactor: add gas_costs_struct to OSConstants

crates/blockifier/src/execution/contract_address_test.rs, crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/execution/syscalls/mod.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1618)
=> refactor: use gas_costs instead of gas_costs_map

crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1620)
=> refactor: delete gas_costs_map

crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
…S_COST_NAMES
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1621)
=> refactor: use ADDITIONAL_FIELDS instead of ALLOWED_GAS_COST_NAMES

crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1661)
=> refactor: rename OSConstants to OsConstants

crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_state_proxy_test.rs, crates/blockifier/src/concurrency/versioned_storage.rs, crates/blockifier/src/concurrency/versioned_storage_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1718)
=> fix(state): ignore writes of the current transaction upon read

crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1720)
=> refactor: make validate_rounding_consts public

crates/blockifier/resources/versioned_constants_13_1.json, crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1721)
=> chore(fee): lower gas cost per code byte

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1722)
=> chore: release v0.6.0-rc.0

commitlint.config.js, crates/blockifier/src/concurrency/scheduler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1702)
=> feat(concurrency): add counters to the scheduler

crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1738)
=> refactor(fee): removed setters from StarknetResources

crates/blockifier/resources/versioned_constants_13_1.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1741)
=> chore: copy v0.13.1 versioned constants

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1745)
=> chore: release v0.6.0-rc.1

crates/native_blockifier/src/py_validator.rs
Was already discussed in: https://reviewable.io/reviews/starkware-libs/blockifier/1678#-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1742)
=> chore: remove todos that already apper on monday

crates/blockifier/src/concurrency/scheduler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1740)
=> fix(concurrency): change u32 to usize

crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1746)
=> refactor: add class_hash to ContractConstructorExecutionFailed error

crates/blockifier/src/concurrency.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_storage.rs, crates/blockifier/src/concurrency/versioned_storage_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1739)
=> fix(concurrency): change version to tx_index

crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1730)
=> refactor: separate statful validator logic from py_validator

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1747)
=> feat(concurrency): add tx_statuses field to the scheduler

crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1731)
=> refactor: add stateful validator error

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1777)
=> chore: bump RC version

crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/utils.rs, crates/blockifier/src/utils_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1632)
=> fix: add strict_subtract_mappings

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/bouncer.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction_execution_info.rs, crates/native_blockifier/src/py_validator.rs
refactor: move bouncer creation to block executor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1783)
=> refactor: pass bouncer_config from python to TransactionExecutor

crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1778)
=> chore: fix import in check_entry_point_execution_error

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs, crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1785)
=> refactor: move BlockFull error

crates/blockifier/src/concurrency.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1776)
=> test(concurrency): test decrease_validation_index

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1790)
=> chore: use the fixture block_context in transaction_test

crates/blockifier/src/concurrency/scheduler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1700)
=> feat(concurrency): add next_task method to the scheduler

crates/blockifier/src/concurrency/scheduler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1701)
=> feat(concurrency): add check_done to the scheduler

crates/blockifier/src/test_utils/initial_test_state.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1798)
=> test: refactor fund_account to get state reader

crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1765)
=> feat(concurrency, state): add declared_contract hashmap to StateCache

crates/blockifier/src/test_utils/initial_test_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1799)
=> test: extract get test state reader function

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1796)
=> test: add the tx_version parameter to faulty_account_tx_args

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1792)
=> test(concurrency): unit test the scheduler

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1797)
=> test: add version related scenarios to tests using faulty account

crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1806)
=> refactor(state): refactor StateCache into two StateMaps objects

crates/blockifier/src/state/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1820)
=> refactor(state): delete state impl for MutRefState

crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1819)
=> feat(state): impl extend for StateMaps

crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1766)
=> feat(concurrency): create an enveloper state for fee transfer

crates/blockifier/src/concurrency/versioned_state_proxy.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1826)
=> refactor(state): use StateMaps in versioned state

crates/blockifier/src/concurrency/versioned_state_proxy.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1832)
=> refactor(state,concurrency): change state method to public and define a mutex guard type

crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_storage.rs, crates/blockifier/src/state/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1680)
=> feat(execution): implement commit chunk method

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1833)
=> test: fail verbosely on test_validate_accounts_tx positive flow

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/bouncer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1829)
=> refactor(execution): move bouncer-related code to its file

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/blockifier/stateful_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1779)
=> test: stateful_validator, skelaton

crates/blockifier/src/transaction/transactions_test.rs
Following the convention set in #1779.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1834)
=> test: improve readablity of test_validate_accounts_tx

Cargo.lock, Cargo.toml, crates/native_blockifier/Cargo.toml, crates/native_blockifier/bench/blockifier_bench.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1824)
=> perf(execution): benchmark random transfers

crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1837)
=> test: add version 2 and 3 declare tx support

crates/blockifier/src/concurrency/test_utils.rs
…st utils
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1835)
=> feat(concurrency): move versioned_state_for_testing to test_utils

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/execution/errors.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/execution/syscalls/hint_processor.rs, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1840)
=> feat: define ctor entry point error

crates/blockifier/src/execution/errors.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/errors.rs, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1844)
=> feat: change constructor error variant in TransactionExecutionError

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/bouncer.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/test_utils.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1841)
=> feat(execution): implement execute_chunk naively

crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_transaction.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1850)
=> refactor(execution): clean PyBlockExecutor

crates/blockifier/src/execution/errors.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1845)
=> feat: add ctor error frame to stack trace

crates/blockifier/src/blockifier/stateful_validator_test.rs, crates/blockifier/src/bouncer_test.rs, crates/blockifier/src/concurrency/versioned_state_proxy_test.rs, crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/execution/syscalls/syscalls_test.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/objects_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1851)
=> refactor: clean tests by using macros

crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1858)
=> chore: fix clippy 1.78 errors

crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_state_proxy_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1846)
=> refactor(state,concurrency): remove state impl from ` VersionedStateProxy ` and edit tests

crates/blockifier/src/concurrency/test_utils.rs, crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_state_proxy_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1748)
=> test(concurrency): add versioned state proxy flow test

crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_state_proxy_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1860)
=> refactor(state,concurrency): add validate read set and apply writes to versioned state proxy

crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1859)
=> feat(execution): implement execute_txs

crates/blockifier/src/blockifier.rs, crates/blockifier/src/blockifier/block.rs, crates/blockifier/src/blockifier/block_test.rs, crates/blockifier/src/blockifier/config.rs, crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1861)
=> feat(execution,concurrency): add ConcurrencyConfig

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1795)
=> feat(concurrency): use tx statuses in the scheduler

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs, crates/blockifier/src/execution/deprecated_syscalls/mod.rs, crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1862)
=> refactor(execution): remove read before deprecated storage write

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1800)
=> feat(concurrency): add finish execution/validation methods to the scheduler

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1874)
=> refactor(execution): rename execute_chunk to execute_txs

crates/blockifier/bench/blockifier_bench.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1883)
=> perf(execution): support executing tx chunks in the transfers benchmark

crates/blockifier/src/concurrency.rs, crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/fee_utils_test.rs, crates/blockifier/src/concurrency/test_utils.rs, crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1773)
=> test(concurrency): add fee utils to concurrency and fix call info

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1801)
=> test(concurrency): test finish execution and finish validation in scheduler

crates/blockifier/src/bouncer.rs, crates/blockifier/src/concurrency.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/utils.rs, crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/versioned_state_proxy_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1882)
=> chore(concurrency): add execute method to the thread logic

crates/blockifier/src/execution/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1852)
=> chore: refactor and split gen_transaction_execution_error_trace

crates/blockifier/src/execution/entry_point_test.rs, crates/blockifier/src/test_utils/contracts.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1853)
=> chore: move PC location test util

crates/blockifier/src/execution/errors.rs, crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1849)
=> feat: implement and test deploy syscall ctor stack trace

crates/blockifier/src/execution/stack_trace.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1856)
=> feat: add VM error frame

crates/blockifier/src/test_utils/dict_state_reader.rs
this is required for the TestStateReaderFactory
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1899)
=> chore: add clone to DictStateReader for Mempool testing

crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1870)
=> feat(concurrency): update sequencer balance in storage

crates/blockifier/src/fee/fee_checks.rs, crates/blockifier/src/transaction/errors.rs, crates/native_blockifier/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1901)
=> fix: clean fee errors

crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1843)
=> feat(concurrency): write commit transaction

crates/blockifier/src/concurrency/scheduler.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1889)
=> feat(concurrency): add commit transaction functionality to the scheduler

crates/blockifier/bench/blockifier_bench.rs, crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/versioned_state_proxy.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1897)
=> test(concurrency): change worker executor field chunk to reference, add test to execute method

crates/blockifier/src/concurrency.rs, crates/blockifier/src/concurrency/test_utils.rs, crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1905)
=> refactor: small renaming

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1894)
=> test(concurrency): test try_commit method of the scheduler

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/bouncer.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1895)
=> chore(native_blockifier): return the block weights to python

crates/blockifier/src/concurrency/test_utils.rs, crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs, crates/blockifier/src/concurrency/versioned_storage.rs, crates/blockifier/src/concurrency/versioned_storage_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1892)
=> feat(concurrency): delete writes

crates/blockifier/src/test_utils.rs, crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/tests/feature_contracts_compatibility_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1866)
=> test: test feature contract files structure and consistency with rust

crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/transaction/objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1903)
=> chore(concurrency): implement validate method in worker logic

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1906)
=> feat(concurrency): add commit transactions phase to worker loop

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1907)
=> chore(concurrency): remove check_done flow from scheduler

crates/blockifier/src/execution/call_info.rs, crates/blockifier/src/execution/entry_point.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/os_usage_test.rs, crates/blockifier/src/state/cached_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1913)
=> feat: remove global step limit bound from production code

crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/test_utils/contracts.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1909)
=> chore(state): use strict_subtract_mappings for compiled classes

crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1910)
=> chore(state): implement diff for StateMaps

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/state/cached_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1911)
=> chore(state): clean to_state_diff

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1775)
=> ci: unify the tests in a ci to one rule

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1914)
=> ci: restore the cargo test in ci

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1891)
=> feat(concurrency): add halt() to scheduler

crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1887)
=> refactor(concurrency): add declared_contracts to versioned_state

crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1804)
=> refactor(concurrency): add deployed contracts check to validate_read_set

crates/blockifier/src/concurrency/worker_logic.rs
overflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1915)
=> fix(concurrency): fix add fee to sequencer balance so it will check u128

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/scheduler_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1904)
=> test(concurrency): test finish_execution_during_commit

crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1898)
=> test(concurrency): test update sequencer balance in storage

crates/blockifier/src/bouncer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1941)
=> chore: move max_capacity selection to BouncerConfig

crates/blockifier/src/bouncer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1940)
=> chore: move get_tx_weights out of the Bouncer

crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1930)
=> feat(concurrency): use the bouncer in concurrent execution

crates/blockifier/src/concurrency/scheduler.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1918)
=> test(concurrency): test commit phase in the worker logic

crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1933)
=> build: add total gas to transactionexecutioninfo

crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1957)
=> fix: errors introduced by merging PR #1918

crates/blockifier/bench/blockifier_bench.rs, crates/blockifier/src/blockifier/block.rs, crates/blockifier/src/blockifier/block_test.rs, crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/blockifier/stateful_validator_test.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/context.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1956)
=> refactor: add BouncerConfig to BlockContext

crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs, crates/native_blockifier/src/state_readers/papyrus_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1962)
=> refactor: remove underscore prefix from functions

crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs, crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/test_utils/struct_impls.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1960)
=> test(concurrency): fix worker test to use non-empty bouncer

crates/blockifier/src/concurrency/versioned_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1949)
=> feat(concurrency): add consumers to the versioned state

crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/concurrency/versioned_state_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1948)
=> refactor(concurrency): use apply_writes in the commit of VersionedState

crates/blockifier/src/concurrency/versioned_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1954)
=> fix(concurrency): remove compiled_class_hashes check from validate_reads

crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1964)
=> chore(native_blockifier): remove unnecessary checks

crates/blockifier/src/blockifier/stateful_validator_test.rs, crates/blockifier/src/execution/stack_trace_test.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/test_utils.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1939)
=> chore: simplify create_account_tx_for_validate_test

crates/blockifier/src/blockifier/block.rs, crates/blockifier/src/blockifier/block_test.rs, crates/blockifier/src/context.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_state_diff.rs, crates/native_blockifier/src/py_utils.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1969)
=> chore: clean pre_process_block

crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/transaction/transaction_execution.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1959)
=> chore: move tx-too-big check to execute_raw

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/fee/actual_cost.rs, crates/blockifier/src/fee/actual_cost_test.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs, crates/blockifier/src/transaction/objects.rs, crates/blockifier/src/transaction/post_execution_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions_test.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1972)
=> refactor: make transactiontreceipt  substruct of transactionexecutioninfo

crates/blockifier/src/transaction/transaction_execution.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1974)
=> fix: merge conflict

crates/blockifier/src/blockifier/config.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1953)
=> feat(concurrency): implement execute_chunk

crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/fee/fee_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1922)
=> test(concurrency): add utilities for commit tx test

crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1893)
=> test(concurrency): write a test for commit transaction

crates/blockifier/src/state/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1997)
=> chore(state): make StateMaps fields public

crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/fee_utils_test.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2003)
=> chore(fee, concurrency): move add_fee_to_sequencer_balance to fee_utils

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2000)
=> chore: use intermediate vars in CI script

crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/worker_logic.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2004)
=> chore(fee, concurrency): move all fee logic to fee_utils

crates/blockifier/bench/blockifier_bench.rs, crates/blockifier/src/blockifier/config.rs, crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/blockifier/transfers_flow_test.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/test_utils/transfers_generator.rs, crates/native_blockifier/src/py_block_executor.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1987)
=> fix(concurrency): assert no concurrency mode in sequential run

crates/native_blockifier/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2010)
=> chore(native_blockifier): turn on concurrency feature

.cargo/config.toml, .github/workflows/ci.yml, BUILD, Dockerfile, build_native_blockifier.sh, crates/native_blockifier/Cargo.toml, scripts/install_build_tools.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2001)
=> chore: publish native blockifier artifacts via CI

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2012)
=> chore: fix clippy and test phases

crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2011)
=> test(concurrency): test the halt flow in the commit phase

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/blockifier/transaction_executor_test.rs, crates/blockifier/src/concurrency/fee_utils.rs, crates/blockifier/src/concurrency/fee_utils_test.rs, crates/blockifier/src/concurrency/test_utils.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/context.rs, crates/blockifier/src/state/cached_state.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/blockifier/src/test_utils/transfers_generator.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2016)
=> refactor(concurrency): remove concurrency_mode from block context

.github/workflows/ci.yml, .github/workflows/compiled_cairo.yml, .github/workflows/coverage.yml, .github/workflows/post-merge.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2017)
=> fix: post merge actions

.github/workflows/ci.yml, .github/workflows/compiled_cairo.yml, .github/workflows/coverage.yml, .github/workflows/post-merge.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2023)
=> chore: reinstate CI cache

scripts/merge_paths.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2026)
=> fix: merge paths

.github/workflows/verify-deps.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2027)
=> fix: verify dependencies CI phase

.github/workflows/ci.yml, crates/blockifier/src/blockifier/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2032)
=> fix: cargo build without testing feature

.github/workflows/ci.yml, crates/blockifier/Cargo.toml, crates/blockifier/src/blockifier/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2033)
=> fix: featureless testing

crates/blockifier/src/blockifier/transaction_executor.rs, crates/blockifier/src/concurrency/test_utils.rs, crates/blockifier/src/concurrency/worker_logic.rs, crates/blockifier/src/transaction/account_transaction.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transaction_execution.rs, crates/blockifier/src/transaction/transactions.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2024)
=> refactor(concurrency): add execution flags struct

crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs, crates/blockifier/src/test_utils/struct_impls.rs, crates/native_blockifier/src/py_block_executor.rs, crates/native_blockifier/src/py_objects.rs
Soon python
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2035)
=> feat(execution): remove special handling of keccak in bouncer

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2036)
=> chore: bump package dev version

.github/workflows/post-merge.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2037)
=> fix: post merge action

.github/workflows/ci.yml, .github/workflows/compiled_cairo.yml, scripts/rust_fmt.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2039)
=> fix: verify contracts and rustfmt phases

crates/blockifier/src/blockifier/stateful_validator.rs, crates/blockifier/src/blockifier/stateful_validator_test.rs
cherry-pick from main: bad24f2543c848202f8fe2c833cd4149fef75d9f
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2034)
=> refactor: remove skip validation checks from stateful validator

crates/blockifier/src/bouncer.rs, crates/blockifier/src/bouncer_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2040)
=> feat: add new builtins to bouncer BuiltinCount

crates/blockifier/resources/versioned_constants.json, crates/blockifier/src/transaction/transactions.rs, crates/blockifier/src/versioned_constants.rs, crates/blockifier/src/versioned_constants_test.rs, crates/native_blockifier/src/py_block_executor.rs
…e in declare V0 and V1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2014)
=> fix(transaction): disable cairo0 redeclaration

crates/blockifier/src/fee/fee_utils.rs, crates/blockifier/src/versioned_constants.rs, crates/native_blockifier/src/py_objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2043)
=> chore: patch range_check name bug

crates/blockifier/resources/versioned_constants.json, crates/blockifier/resources/versioned_constants_13_0.json, crates/blockifier/resources/versioned_constants_13_1.json, crates/blockifier/resources/versioned_constants_13_1_1.json, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/execution_flavors_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2044)
=> chore: update costs

crates/blockifier/resources/versioned_constants.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2045)
=> chore: update max calldata length

crates/blockifier/bench/blockifier_bench.rs, crates/blockifier/src/blockifier/transfers_flow_test.rs, crates/blockifier/src/test_utils/transfers_generator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1921)
=> test(execution): support disjoint recipients in transfers flow test

crates/blockifier/bench/blockifier_bench.rs, crates/blockifier/src/blockifier/transfers_flow_test.rs, crates/blockifier/src/test_utils/transfers_generator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1945)
=> chore: add a config struct for transfers generator

crates/blockifier/src/concurrency/fee_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2057)
=> chore(concurrency): support fee token proxy pattern

crates/blockifier/src/bouncer.rs, crates/native_blockifier/src/errors.rs, crates/native_blockifier/src/py_objects.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2048)
=> fix(native_blockifier): returns an error when a builtin is missed from the bouncer config

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2056)
=> chore: prep for RC

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2058)
=> chore: bump sn-api version to RC

crates/blockifier/src/concurrency/versioned_state.rs, crates/blockifier/src/state/cached_state.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2059)
=> chore: reassign todos

.github/workflows/post-merge.yml, crates/blockifier/tests/requirements.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2062)
=> chore: fix post-merge by strict install sympy==1.12.0

crates/blockifier/src/concurrency/fee_utils_test.rs, crates/blockifier/src/concurrency/worker_logic_test.rs, crates/blockifier/src/test_utils/declare.rs, crates/blockifier/src/transaction/account_transactions_test.rs, crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2065)
=> fix(transaction): change declare default version to be V3

crates/blockifier/src/concurrency/worker_logic_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2052)
=> test(concurrency): add cairo0 contracts to deploy then declaer

crates/blockifier/src/transaction/transactions_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2050)
=> fix(concurrency): test disable re-declaration of cairo0 contracts

crates/blockifier/src/transaction/error_format_test.rs, crates/blockifier/src/transaction/errors.rs
**Stack**:
- #2078
- #2073
- #2072 ⬅
- #2069
- #2082
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2072)
=> fix:  invalid version format

crates/blockifier/src/transaction/error_format_test.rs, crates/blockifier/src/transaction/errors.rs
commit-id:85a8a843
---
**Stack**:
- #2078
- #2073 ⬅
=> fix:  invalid nonce format

crates/blockifier/resources/versioned_constants.json, crates/blockifier/resources/versioned_constants_13_0.json, crates/blockifier/resources/versioned_constants_13_1.json, crates/blockifier/resources/versioned_constants_13_1_1.json, crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/execution/execution_utils.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2090)
=> fix: offset segment arena instance counter for older vm versions

crates/blockifier/resources/versioned_constants.json, crates/blockifier/resources/versioned_constants_13_0.json, crates/blockifier/resources/versioned_constants_13_1.json, crates/blockifier/resources/versioned_constants_13_1_1.json, crates/blockifier/src/execution/deprecated_entry_point_execution.rs, crates/blockifier/src/execution/entry_point_execution.rs, crates/blockifier/src/versioned_constants.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2095)
=> chore: rename segment arena flag in versioned constants
