starkware-libs/blockifier

README.md
docs/SECURITY.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/224)

Fix readme paths

---

crates/blockifier/src/state/papyrus_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/227)

Remove old TODO

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/222)

Add `DelegateCall` syscall.

---

crates/blockifier/feature_contracts/compiled/account_without_validations_compiled.json
crates/blockifier/feature_contracts/compiled/empty_contract_compiled.json
crates/blockifier/feature_contracts/compiled/security_tests_contract_compiled.json
crates/blockifier/feature_contracts/compiled/test_contract_compiled.json
crates/blockifier/tests/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/230)

Remove cairo version constraint

---

.github/workflows/compiled_cairo.yml

If someone touches cairo source code or compiled contracts, they must pass the verification check before being merged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/231)

Add cairo file verification workflow

---

crates/native_blockifier/Cargo.lock
crates/native_blockifier/build_wheels.sh
crates/native_blockifier/native_blockifier/__init__.py
crates/native_blockifier/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/234)

Rename remaining python_rust_bridge references into native_blockifier

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs

I tested it manually and added a Monday task to add tests for faulty account implementations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/241)

Add `verify_no_calls_to_other_contracts`.

---

crates/blockifier/src/state/errors.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/242)

Validate invoke transaction entry point.

---

crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/244)

Add `SyscallSelector` enum.

---

crates/native_blockifier/build_wheels.sh

We're probably going to dump pypy, but let's add this just to be safe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/245)

Fix wheel generation - also generate for pypy

---

crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/247)

Add syscall counter to `SyscallHintProcessor.`

---

crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls_test.rs
crates/blockifier/src/state/papyrus_state_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/246)

Move events and messages to L1 to `CallExecution`.

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/251)

fix clippy

---

crates/native_blockifier/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/252)

Add return-value test for native_blockifier

---

crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/248)

Fix master.

---

crates/native_blockifier/build_wheels.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/254)

Fix Dependency in build_wheels.

---

crates/blockifier/src/transaction.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/255)

Execute general transactions.

---

Cargo.lock
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/state/papyrus_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/256)

Fix changes in cairo-vm and starknet-api.

---

crates/blockifier/src/execution/execution_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/257)

Castle cairo runner and vm args.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/259)

Return StateDiff from Transaction's execute().

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/265)

Derive debug for Transaction.

---

Cargo.lock
crates/native_blockifier/Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/261)

Get invoke tx in from python.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/264)

Get txs from python.

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/268)

Create a Python tx executor class with a saved state and block context.

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/build_wheels.sh
crates/native_blockifier/src/lib.rs

- Wrap papyrus_storage with a dedicated class to hide the implementation.
- Implement initialization API.
- Add error handling.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/262)

Initial storage implementation for native blockifier

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/273)

 Add to the State trait the method: `set_contract_class()`.

---

Cargo.lock
crates/native_blockifier/Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/263)

Add remaining native-blockifier methods required for DB sync

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

In a subsequent PR I will pass the `contract_class` from `PyExecutor.execute`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/276)

Add class to Declare AccountTransaction variant.

---

Cargo.lock
crates/blockifier/src/execution/entry_point_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/275)

Uncomment fixed security tests.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/274)

Allow returning a PyStateDiff to python

---

crates/native_blockifier/src/py_transaction.rs

Signed-off-by: Dori Medini <dori@starkware.co>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/278)

Implemented finalize()

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/280)

Receive a contract class from python in execute.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/284)

Return `StateDiff` and `TransactionExecutionInfo` from `PyExecutor.execute()`.

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/287)

Rename class argument from Python to `raw_contract_class`.

---

crates/native_blockifier/src/py_state_diff.rs

Must have been deleted in a merge conflict.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/289)

Readd FromPyObject to PyStateDiff

---

crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/292)

Change execute declare: add the mapping class_hash <-> contract_class.

---

crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/293)

Add fields to `PyCallInfo` so it will be identical to the pythonic class.

---

crates/native_blockifier/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/297)

Add structs to native_blockifier.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/298)

Skip charge_fee in case max_fee is 0 (for testing).

---

crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/299)

Handle the case of declaring an already declared contract.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_test_utils.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/296)

Create intiail state for Python testing.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/300)

Convert `dyn State` to parametrized.

---

crates/blockifier/src/state/cached_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/302)

impl Merge for CachedState

---

crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/301)

Added (empty) field, updated converters

---

crates/blockifier/src/execution/entry_point_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/303)

Uncomment security test.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/306)

Add order to events and l2 to l1 messages.

---

crates/blockifier/src/state/cached_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/310)

Add `MutRefState`.

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/311)

Don't handle nonce in Txs of version 0.

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/native_blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/308)

Run cargo update and fix errors

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/269)

Add an account transactions flow test.

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/305)

Use Papyrus storage in PyTransactionExecutor's state.

---

crates/blockifier/src/transaction/errors.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/312)

Fix chain ID construction

---

crates/blockifier/src/execution/entry_point_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/320)

Change to unknown value for memory cell error message.

---

crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/316)

Add transactional execution functionality.

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/321)

Use actual papyrus storage in PyTransactionExecutor.

---

crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/323)

Add execution resource fields to PyTransactionExecutionInfo.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/execution/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/314)

Add storage related members to the syscall handler.

---

crates/blockifier/src/execution/execution_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/327)

Run VM with trace enabled.

---

crates/native_blockifier/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/329)

Bump blockifier version to 0.13.0.

---

crates/blockifier/src/test_utils.rs
crates/native_blockifier/setup.py
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/330)

Verify the executors storage is aligned with the main storage.

---

crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/326)

Pass file max size to Papyrus reader.

---

crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/336)

Fix eth address -> felt conversion

---

crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/332)

Add mark_address_range_as_accessed.

---

crates/blockifier/src/abi/constants.rs
crates/native_blockifier/setup.py
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/341)

Set version field in L1 handler to 0 (when converting from the pythonic object)

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/340)

Fix event and messages-to-L1 order.

---

Cargo.lock
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/337)

Change code according to dependecies' changes.

---

Cargo.lock
crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/execution_utils_test.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/345)

Cargo update.

---

.gitignore
BUILD
WORKSPACE
crates/BUILD
crates/native_blockifier/BUILD
crates/native_blockifier/native_blockifier/BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/339)

add bazel support to build blockifier

---

crates/native_blockifier/setup.py
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/346)

Renaming some variables.

---

crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/348)

Complete VM resources logic.

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/344)

Handle __default__ in resolve_entry_point_pc

---

Cargo.lock
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/350)

Cargo update; use `+= &rhs` on VM resources.

---

crates/blockifier/feature_contracts/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/test_contract.cairo
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/tests/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/356)

Fix retdata size extraction.

---

crates/native_blockifier/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/361)

Bump `native_blockifier` version.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/335)

Count actual state changes.

---

crates/native_blockifier/setup.py
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/362)

Make previous_block_id optional.

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/364)

Add storage changes to TransactionExecutionInfo.

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/fee/gas_usage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/367)

Add get_onchain_data_segment_length.

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/fee/os_resources.json
crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/transaction/transaction_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/360)

Deserialize os resources from file

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/execution_utils.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/setup.py
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/368)

Correctly initialize VM resources in `PyTransactionExecutionInfo`.

---

crates/blockifier/feature_contracts/compiled/account_without_validations_compiled.json
crates/blockifier/feature_contracts/compiled/empty_contract_compiled.json
crates/blockifier/feature_contracts/compiled/security_tests_contract_compiled.json
crates/blockifier/feature_contracts/compiled/test_contract_compiled.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/370)

Fixed cairo compiled files

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/fee/gas_usage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/366)

Added get_message_segment_length.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/transaction/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/363)

Add get_sorted_l2_to_l1_payloads_length.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/papyrus_state.rs
crates/blockifier/src/state/papyrus_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/277)

Return `Arc<ContractClass>` from `get_contract_class()` API.

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/fee/gas_usage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/377)

Add 'get_consumed_message_to_l2_emissions_cost'.

---

crates/blockifier/src/fee/eth_gas_constants.rs
crates/blockifier/src/fee/gas_usage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/379)

Add `calculate_tx_gas_usage`.

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/native_blockifier/Cargo.toml

Needed for Bazel integration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/381)

Lock cairo-rs version

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/373)

Added gas_price to block_context.

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/390)

Forbid class redeclaration in Declare V2 only.

---

crates/blockifier/ERC20_without_some_syscalls/ERC20/erc20_contract_without_some_syscalls_compiled.json
crates/blockifier/feature_contracts/account_faulty.cairo
crates/blockifier/feature_contracts/compiled/account_faulty_compiled.json
crates/blockifier/feature_contracts/compiled/empty_contract_compiled.json
crates/blockifier/feature_contracts/compiled/security_tests_contract_compiled.json
crates/blockifier/feature_contracts/compiled/test_contract_compiled.json
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/266)

Add validate positive flow test.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/386)

Add `calculate_tx_resources`.

---

Cargo.lock
Cargo.toml
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/359)

More informative entry point errors

---

crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/401)

Absolute contract path

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/state.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/402)

Move payrus storage to native_blockifier

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/fee/fee_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/397)

Change the weights in cairo_resource_fee_weights to float.

---

crates/blockifier/src/fee/fee_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/404)

Fix conflict in test_calculate_l1_gas_by_cairo_usage.

---

crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/410)

Rename and document `Storage`.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/411)

Add contract address to `InvalidNonce` error.

---

crates/native_blockifier/src/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/357)

Expose native blockifier error names to python

---

crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/os_usage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/399)

Add calculate_tx_fee.

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/413)

Added test_calculate_tx_gas_usage_basic.

---

crates/blockifier/src/fee/gas_usage_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/415)

Changed Deploy to DeployAccount.

---

crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/408)

Add `actual_resources` to `PyTransactionExecutionInfo`.

---

crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/412)

Call calculate_tx_fee.

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/416)

Remove counters from TransactionExecutionInfo.

---

crates/blockifier/feature_contracts/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/test_contract.cairo
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/constants.rs
crates/blockifier/src/transaction/transaction_types.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/270)

Add negative flows to validate unit test.

---

Cargo.lock
Cargo.toml
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls_test.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/418)

Update cairo-vm revision.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/execution/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/417)

Add code address to entry point.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/419)

Remove code address from external entry points.

---

crates/native_blockifier/BUILD

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/420)

build in pypy mode

---

Cargo.lock
Cargo.toml

Also alphabetize deps and remove unnecessary comment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/425)

Bump cairo-rs - performance optimizations added

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/execution_utils_test.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/432)

Remove `cairo-felt` dependency (exported from `cairo-vm`).

---

Cargo.lock
Cargo.toml
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/429)

Support Invoke V0.

---

crates/blockifier/feature_contracts/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/test_contract.cairo
crates/blockifier/src/execution/deprecated_syscall_hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls.rs
crates/blockifier/src/execution/deprecated_syscalls_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/hint_code.rs
crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/436)

Implement the  syscall.

---

crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/439)

Use .into() to convert errors.

---

crates/blockifier/src/execution/deprecated_syscalls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/438)

Alphabetize syscall implementations.

---

Cargo.toml
crates/native_blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/444)

Simplify Cargo.toml

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/442)

Wrap declare tx and contract class with struct.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/437)

Setting the compiled hash under the class hash in declare version 2.

---

crates/blockifier/src/execution.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/449)

New syscalls

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/451)

Refactor Syscall reads and writes

---

crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/453)

Rename `get_contract_class` -> `get_compiled_contract_class`

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/450)

Gas handling in new syscalls

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/457)

Execution context refactor

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/458)

Use ContractClass enum in blockifier

---

crates/blockifier/src/execution.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/459)

Separate Cairo0 execution

---

crates/blockifier/src/execution.rs
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/460)

Copy v0 execution code

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/execution_utils_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/462)

Upgrade cairo-vm

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/execution_utils_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/461)

Start supporting Cairo1 execution

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/463)

Use cairo-lang hint execution

---

crates/native_blockifier/src/py_utils.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/471)

Change `previous_block_id` to `PyFelt`.

---

crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/475)

Allow declaring a class that was already declared (for V0V1).

---

crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/474)

Get declared classes from python and write it to the storage (via `append_block`)

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/476)

Handle None nonce passed from Python (in InvokeV0).

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/464)

Prepare cairo1 vm for entrypoint call

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/465)

Prepare segment arena Segment

---

crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/466)

Cairo1 read and write syscalls

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/482)

Delete deprecated syscalls (from new syscall files).

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/447)

Return executed compiled class hashes to Python.

---

crates/blockifier/src/execution.rs
crates/blockifier/src/execution/contract_address.rs
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/487)

Move test_calculate_contract_address to a different file.

---

crates/blockifier/tests/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/488)

No quotes in cairo-lang version

---

crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/480)

Check for sufficient L1 fee paid for L1HandlerTransaction.

---

Cargo.lock
Cargo.toml
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state_test.rs

StarFelt now has a bunch of casts, so `from`s need to be explicit
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/492)

Bump SN API and Papyrus

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/491)

Decouple max_fee from balance in tests.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/496)

Add `CallEntryPoint` member to `SyscallHintProcessor`.

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/489)

Add paid_fee_on_l1 arg to python args.

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/entry_point_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/498)

Move `test_stack_trace` from deprecated test file.

---

crates/blockifier/feature_contracts/cairo1/compiled/empty_contract.casm.json
crates/blockifier/feature_contracts/cairo1/empty_contract.cairo
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/486)

Tidy-up test utils.

---

Cargo.lock
crates/blockifier/src/test_utils.rs
crates/blockifier/src/utils.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/473)

Supporting declare version 2 in py transaction.

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/501)

Implement get_balance on State

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/481)

Failed cairo1 execution

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/503)

Get paid_fee_on_l1 from tx.

---

crates/native_blockifier/src/papyrus_state.rs

Currently unused, will soon replace `StateReader`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/506)

Add `Papyrus` casm reader and bundle with `StateReader` in `PapyrusReader`

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/state/cached_state.rs
crates/native_blockifier/src/papyrus_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/507)

Fix whitespace and reorder items

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/504)

Separate validate-execute state changes

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/utils.rs
crates/native_blockifier/src/py_test_utils.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/505)

Add a `try_from_json_string` and a `from_path` methods in the contract structs

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_transaction.rs

to enforce compatibility between declare version and the cairo version.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/468)

Add a `new()` method to `DeclareTransaction` struct 

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/477)

Add two additional fields to `CallExecution`: `gas_consumed` and `failure_flag`.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/494)

Check balance is at least max_fee

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/510)

Newly private field access

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/520)

cherry-pick - Get paid_fee_on_l1 from tx. (#503)

---

crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/state/state_api.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/524)

Extract Uint256 storage var getter

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/527)

No fee enforcement if max_fee == 0

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/528)

Failed cairo1 execution (#481)

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/utils.rs
crates/native_blockifier/src/py_test_utils.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/534)

Add a `try_from_json_string` and a `from_path` methods in the contract structs. (#505)

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/535)

Add a new method to DeclareTransaction struct (to enforce compatibility between declare version and the cairo version). (#468)

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/536)

Add two additional fields to CallExecution: gas_consumed and failure_flag. (#477)

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/state/cached_state.rs
crates/native_blockifier/src/papyrus_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/538)

Fix whitespace and reorder items (#507)

---

crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/transaction/transactions_test.rs

- Following the PR: Add keccak syscall support. [#29729](https://github.com/starkware-industries/starkware/pull/29729)
- According to [os_resources.json](https://github.com/starkware-industries/starkware/blob/31d1934aa8ed96c5f10486829d0c58c1d445c4c7/src/starkware/starknet/business_logic/execution/os_resources.json#L1)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/543)

Update `os_resources` file

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/516)

Change `gas_counter` field to be of type `Felt252` so we are able to do arithmetic operation with it.

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/542)

Return executed compiled class sizes to Python.

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/554)

Add version = 2 for the allowed versions of declare transactions.

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/556)

Implement Casm hash calc. est. for Cairo0 class.

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/558)

Use `derive_more` for `ContractClass`

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/544)

Add max_steps to ExecutionContext

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/560)

Rustier syntax

---

crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/562)

Do not read from storage before writing in `storage_write`.

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/contract_class.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/564)

Implement Casm hash calc. est. for Cairo0 class. (#556)

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/565)

Elin/merge main v0.12.0 into main

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/563)

Disallow V1 -> V0 class replacement.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/contract_class.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/566)

Implement Casm hash calc. est. for Cairo1 class.

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/570)

Trigger CI for feature branches

---

crates/blockifier/src/execution/execution_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/574)

Handle case where program attributes are Null.

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/582)

Specify other main branches reges in CI file.

---

crates/native_blockifier/src/storage.rs

As is done with `deprecated_declared_classes`.
This has quite a bit of duplication with the `deprecated_declared_classes` logic just above it (crates/native_blockifier/src/storage.rs:125), any way of removing the duplication?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/559)

Only add undeclared classes to declared_classes

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

Based on #545.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/546)

Pass remaining_gas between shared calls.

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/transaction_execution.rs

Based on #546.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/547)

Pass gas to cairo1 syscalls

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/555)

Get gas_consumed from the return values of the execution.

---

Cargo.lock
Cargo.toml
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/583)

Update cairo vm version.

---

crates/blockifier/src/execution/errors.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/591)

Get initial gas inside `execute_raw`.

---

crates/blockifier/src/fee/os_usage_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/587)

Builtin name consistency test

---

crates/native_blockifier/src/storage.rs

Even if this worked, it's not intuitive.
Now using read transactions for reading and creating the write tx later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/596)

Don't make loop depend on open transaction results.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/597)

Rename: `ExecutionContext` to `EntryPointExecutionContext`.

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/598)

Align starknet-crypto dependency.

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/600)

Remove process_cairo_resource_fee_weights.

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/602)

Update Cairo version.

---

crates/native_blockifier/src/storage.rs

Add replaced classes to append_block
- Hopefully fixes sporadic hint error during execution, of undeclared class_hash.
Not sure why this was sporadic though
- Hoisted the reused `state_number`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/595)

Add replaced classes to append_block

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/569)

Add PyGeneralConfig to avoid using `get_attr`.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/614)

Move `resources` out of `EntryPointExecutionContext`.

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/615)

Instantiate execution context inside `validate_tx`.

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/616)

Instantiate execution context separately, for `run_execute`.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/617)

Add `vm_run_resources` to `EntryPointExecutionContext`.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/619)

Add a TODO to handle `n_steps` run limitation.

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/572)

Apply validate+nonce changes on execution failures

---

crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/613)

Fix segment_arena resource counting.

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/628)

Add NonceManager

---

crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/626)

Transaction execution failures log-level warn->debug

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/631)

Fix recursion depth count.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/633)

Expose chain names to python

---

crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/634)

Add PRIVATE_SN_POTC_MOCK_GOERLI chain name.

---

crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/576)

Move more test utils

---

Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/624)

Add comment in `Cargo.toml`.

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/644)

Update compiler and papyrus versions.

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/645)

Fix recursion bug.

---

crates/blockifier/src/block_execution.rs
crates/blockifier/src/block_execution_test.rs
crates/blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/608)

Add block pre process to blockifier

---

crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/656)

Fix signature pointer in Cairo 1 allocate_tx_info_segment().

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/655)

Better parametrization

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/657)

Return Casm hash calc. est. to Python.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/662)

Disable trace.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_transaction_executor.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/661)

Separate `PyTransactionExecutor` to its own file.

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/667)

Use `update_remaining_gas` in more locations.

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/641)

Add STORED_BLOCK_HASH_BUFFER and enforce it.

---

crates/blockifier/src/abi/constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/672)

Decrease max recursion depth.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/577)

Make sure state doesn't change on failing account deploy tx

---

.github/workflows/ci.yml
scripts/clippy.sh
scripts/rust_fmt.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/669)

Add rust_fmt and clippy scripts.

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/682)

Fix big in RunResources propagation

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/674)

Fix CI rust version: was running nightly instead of stable

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/676)

Change ` gas_consumed ` to be of type ` u64 ` .

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/679)

Change ` gas_counter ` to be of type ` u64 ` .

---

crates/native_blockifier/src/py_transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/665)

Change Bouncer callback from Executor.

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/685)

Bump cairo lang

---

crates/blockifier/src/fee/os_resources.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/681)

Fix keccak resources.

---

crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/secp.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/689)

Add Secp256k1 get xy request and response structs.

---

crates/blockifier/src/transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/691)

Add transaction::test_utils to `testing`

---

crates/blockifier/src/execution/syscalls/secp.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/694)

Add structs for secp256k1 ec operations.

---

crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/700)

Enforce constructor's name to be 'contsructor'.

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/secp.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/698)

Secp256k1GetPointFromXRequest structs.

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/703)

Update compiler version.

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/684)

Enforce minimal fee

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/677)

add n_reverted_steps to the flow

---

crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/state/state_api.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/704)

Cherry pick: Extract Uint256 storage var getter (#524)

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/705)

Cherry pick: Use assert_eq on execution info objects (#525)

---

crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/711)

Update the ACCOUNT_CONTRACT_PATH name to CAIRO0_ACCOUNT_CONTRACT_PATH

---

crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/668)

Convert felt252 to u64.

---

crates/blockifier/src/fee/gas_usage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/713)

Consider the os resources only in calculating the minimal fee.

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/native_blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/716)

Make the repo crates.io friendly

---

Cargo.lock
Cargo.toml
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction_executor.rs
crates/native_blockifier/src/storage.rs

Will update to papyrus_storage crate when published (In this PR).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/715)

Use SN API and papyrus storage published crates.

---

Cargo.lock
Cargo.toml
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction_executor.rs
crates/native_blockifier/src/storage.rs

Python: https://github.com/starkware-industries/starkware/pull/30748/files
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/722)

Revert "Use SN API and papyrus storage published crates. (#715)"

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/726)

Use ` StateChanges ` struct in ` calculate_l1_gas_usage ` flow.

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/724)

Add declare DA cost.

---

.github/workflows/ci.yml
.github/workflows/compiled_cairo.yml
.github/workflows/post-merge.yml
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/hint_code.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/transaction/transactions.rs
scripts/rust_fmt.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/737)

Update the nightly version that is used for formatting.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/736)

Cherry-pick: Mark program's extra data as accessed memory. (#717)

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/712)

Correctly calculating the state changes regarding balance changes.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/744)

move n_reverted_steps addition out of calculate_tx_resources

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/738)

limit execution steps based on provided fee

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

Also, disregard the sequencer in this computation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/749)

Use fee token address in count actual state changes for fee charge.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/751)

move fee and resource calc into a dedicated function

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/storage.rs

This reverts commit a6e8408b475338086076d6a702df1856a9a13e79.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/760)

Revert "Storage cleanup (#731)"

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/762)

Create StateChangesCount struct and use it

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/storage.rs

This reverts commit 69022e5d4b9db656dfe27745784abde3ef65364c.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/771)

Revert "Storage cleanup (#767)"

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/774)

Implement run_invoke_tx for testing

---

Cargo.lock
Cargo.toml
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/763)

Update SN API and Papyrus storage dependencies.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/785)

Add ` validate ` flag indicating if we want to run the validate entrypoint (used for simulation and fee estimation).

---

crates/blockifier/src/execution/syscalls/secp.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/786)

Check the parity of y in non-montgomery form.

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/790)

add StateChanges::merge(..) and some small fixes (renames etc)

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/794)

pass state_changes_count directly to functions instead of state

---

.github/.codecov.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
README.md

- Add code coverage action in github, currently not `required`.
- Add code coverage badge on README.
- Bump github action version
- README update stale roadmap + autoformat
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/782)

Add coverage + small fixes

---

Cargo.lock
Cargo.toml
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/792)

Update SN API before version release.

---

crates/native_blockifier/src/py_transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/798)

Use the ` sequencer_address ` from the block info and not the general config.

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/799)

better name and documentation for test_insufficient_max_fee_reverts

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/800)

Bump version to 0.1.0-rc1

---

crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/809)

move fee and resource calculation closer to execution

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/811)

check that user has enough remaining balance to pay for tx before committing changes. else, revert.

---

Cargo.lock
Cargo.toml
crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/815)

Elin/merge main v0.12.2 into main

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/819)

Updates cache with initial cell values for compiled class hash.

---

Cargo.lock
Cargo.toml
crates/native_blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/825)

Bump version `v0.1.0-rc2 -> v0.2.0-rc0`.

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/810)

Add a fee token address

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_block_executor.rs

This reverts commit 9625ebe5c927dd143db9567d457ba4a6d60aad9f.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/826)

Revert "Add a fee token address (#810)"

---

crates/blockifier/src/execution.rs
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/828)

Move `CallInfo`-related structs to their own file.

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/830)

rename fee_token_address into deprecated_fee_token_address

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/833)

Remove ` count_actual_state_changes ` from docs and test name.

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/832)

Replace *py_felt_sequence_attr method.*

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/834)

Delete *py_felt_attr* and replace every usage with *py_attr*.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/836)

New fee token TODOs

---

Cargo.lock
crates/blockifier/src/test_utils.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/bench/blockifier_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/618)

Simple benchmark

---

crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/840)

Update the os resources.

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/823)

Use stable clippy.

---

crates/blockifier/src/state/cached_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/846)

State changes test doesn't need multiple fee token versions

---

crates/blockifier/src/state/cached_state.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/851)

No special treatment required

---

crates/blockifier/src/abi.rs
crates/blockifier/src/abi/abi_utils_test.rs
crates/blockifier/src/abi/sierra_types.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/secp.rs

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/854)

Add sierra_types.rs with SierraU128 and Sierra initial implementation (from_memory).

---

crates/blockifier/src/abi/sierra_types.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/856)

Add from_storage to CairoU128 impl.

---

crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/transaction_executor.rs

No need for hardcoded `PapyrusReader` now that `TransactionExecutor` is no longer a `pyclass`.
This is also a setup for adding a new `PythonStateReader`.
Python: https://reviewable.io/reviews/starkware-industries/starkware/31597
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/855)

Make `TransactionExecutor` generic

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/secp.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/864)

Add SecpHintProcessor.

---

crates/blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/877)

Fix merge conflict error

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_state_diff.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/868)

Added strk_l1_gas_price to PyBlockInfo & BlockContext.

---

crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/880)

PyStrkL1GasPriceSourceConfig

---

crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/881)

Add override field

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/843)

Rename gas price

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/886)

Return an error for unsupported versions.

---

crates/blockifier/src/block_context.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/893)

Dynamic gas price

---

crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/887)

Define get_strk_gas_price on executor

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_block_executor.rs

Implemented exactly like with `FeeTokenAddresses`. If this pattern is used once more, replace all three with a generic implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/894)

Bundle eth/strk gas prices in `GasPrices`

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/896)

impl HasTransactionVersion for AccountTransaction

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/905)

Remove redundant ExecutionResources

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/884)

Use correct gas price in max invoke steps

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/897)

Remove implementation of trait

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs
crates/native_blockifier/src/py_transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/914)

Elin/merge main v0.12.2 into main v0.12.3

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/916)

Bump version to 0.2.0-rc1

---

Cargo.lock
Cargo.toml
crates/native_blockifier/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/919)

Connect native_blockifier to workspace after upgrade.

---

Cargo.lock
Cargo.toml
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/920)

Barak/upgrade native blockifier to 0.3.0 rc0

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/902)

Migrate to using FeeType

---

crates/blockifier/src/transaction/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/848)

Add another fee token in test init state

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/908)

create_state and create_test_init_data update

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/925)

add charge_fee flag to revertible txs

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/891)

Make `execute_fee_transfer` depend on transaction version.

---

crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/906)

Add max_strk_l1_gas_price

---

crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/909)

Update expected_fee_transfer_call_info for fee types

---

crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/885)

calculate_tx_fee may use strk gas price

---

crates/blockifier/src/fee.rs
crates/blockifier/src/fee/errors.rs
crates/blockifier/src/fee/strk_gas_price.rs
crates/blockifier/src/fee/strk_gas_price_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/928)

Objects and methods for STRK gas price calculation

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/935)

Minimal changes to prep for MUXing

---

crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/929)

Fix py_account_data_context

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/956)

Define `get_tx_account_context` method for each transaction.

---

crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_declare.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/950)

Refactor `DeclareTransaction` creation in `native_blockifier`.

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/938)

Add invoke v0 to invoke_tx, add test case

---

crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/957)

Use ` py_attr ` .

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_deploy_account.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/959)

Refactor `DeployAccountTransaction` creation in `native_blockifier`.

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_deploy_account.rs
crates/native_blockifier/src/py_invoke_function.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/960)

Refactor `InvokeTransaction` creation in `native_blockifier`.

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/947)

Change AccountTransactionContext struct to enum.

---

crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/961)

Change DeprecatedAccountTransactionContext fields from public to private

---

crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/926)

Add ExecutionMode enum to EntryPointExecutionContext.

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/946)

Custom Derive for InvokeTxArgs

---

crates/blockifier/src/transaction/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/948)

Macrofiy From<InvokeVX> for Invoke

---

.github/workflows/ci.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/962)

Trigger CI when base-branch is changed

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/949)

Support and test V3 invoke

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/952)

Remove nonce_manager arg, pass nonce directly

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/954)

Fund test account with all fee types

---

crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/955)

Take a wild guess

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/953)

invoke_tx_args macro

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/937)

Set execution mode as validate for deploy-account transaction.

---

crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/967)

Change DeprecatedAccountTxContext fields from private to public.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/968)

Add CurrentAccountTxContext with CommonFields object.

---

crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/910)

Update validate_final_balances and usages

---

crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/state/cached_state.rs

Alphabetize derived attributes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/963)

Fix order of derived attributes.

---

crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/970)

Add V3 support in get_account_tx_context.

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

This will be used by gateway APIs that wish to validate directly from the gateway.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/879)

Add `validate_tx` to `Transaction` API

---

crates/blockifier/src/execution/common_hints.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/922)

Restrict the use of get_block_hash syscall in during validate.

---

crates/native_blockifier/src/py_invoke_function.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/975)

fix PyInvokeTransactionV0 sender_address field

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/981)

Limit characters in trace until TODO is complete

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/986)

Remove `max_fee` getter from `AccountTransaction`.

---

crates/blockifier/src/transaction/transactions.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/989)

Remove `max_fee` getter from transactions.

---

crates/blockifier/src/transaction/account_transaction.rs

commit-id:16171e18
---
**Stack**:
- #993
- #992
- #991
- #990 ⬅

Simplify `validate_steps` calculation using `Option::map`

---

crates/blockifier/src/abi/constants.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_declare.rs
crates/native_blockifier/src/py_deploy_account.rs
crates/native_blockifier/src/py_invoke_function.rs
crates/native_blockifier/src/py_l1_handler.rs
crates/native_blockifier/src/py_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/969)

Refactor L1 handler creation in `native_blockifier`.

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

Verify the syscall call contract is never calling other contracts in validate mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/940)

Verify the syscall call_contract in validate mode.

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/994)

Better test_call_contract

---

crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs

Moving stuff around, no internal changes:
- move `verify_contract_class_version` into transaction_utils
- hoist `impl L1HandlerTransaction` up so that it appears after the struct definition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1006)

Organize transaction[_utils] (no logic changes)

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/964)

Remove redundant invoke_tx implementation in transaction_test

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/mod.rs

I am adding tests in this PR or the next one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1014)

Block syscalls of type get_block_info in validate.

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/entry_point_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1016)

Test deprecated syscalls of type get_block_info in validate mode.

---

Cargo.lock
Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1022)

Bump Blockifier version to `0.4.0-rc0` for publication.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1023)

Add and use getter

---

crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1018)

Extract code to function

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/transaction/account_transactions_test.rs

- Introduced `RecursionDepthGuard` to manage `current_recursion_depth` in `EntryPointExecutionContext`.
- Eliminates potential bugs arising from early exit (`?`) by ensuring each increment has a matching decrement via `Drop` impl.
- Simplifies error-prone manual increment/decrement.
- Large change around let `result =` due to obviating the need for result variable; logic remains unchanged.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1012)

Refactor Recursion Depth Management with `Guard` Pattern

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1028)

Remove redundant code

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1034)

Do not revert in case of insufficient fee and the charge fee flag is false.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/os_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1037)

Add ` validate ` flag indicating if we want to run the validate entry point (used for simulation and fee estimation). (#785)

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1033)

Do not revert in case of charge fee flag is false and the actual fee exceeds the max fee.

---

crates/blockifier/src/fee/fee_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1040)

Split L1 gas computation to function

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1036)

V3 support in max_invoke_steps

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1026)

Limit validate steps + test

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1050)

Validate: revert some restrictions.

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1032)

Extract post-execution checks

---

crates/blockifier/src/transaction/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1051)

Allow using Cairo1 test contract in transaction test.

---

crates/blockifier/src/execution/entry_point.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1055)

Fix underflow in subtract_steps

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1057)

Revert zero block number for validate.

---

crates/blockifier/src/execution/syscalls/hint_processor.rs

Align TODO message with the correct line.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1059)

Fix TODO message.

---

crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/transaction/transactions_test.rs

See [#31617](https://github.com/starkware-industries/starkware/pull/31617).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1062)

Update os resources to match python STARKNET-RC-0.12.3.0.

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1038)

Reduce boilerplate

---

crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/984)

Update TxInfo syscall

---

crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/988)

Refactor to use allocate_data_segment method

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

[Python](https://reviewable.io/reviews/starkware-industries/starkware/32380)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1052)

Add external transactions.

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1044)

Remove (some) max_fee() usages

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

[Python](https://reviewable.io/reviews/starkware-industries/starkware/32381).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1053)

Add simulate flag to external transactions.

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/constants.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_transaction.rs

[Python](https://reviewable.io/reviews/starkware-industries/starkware/32382)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1063)

 Add simulate flag to ` AccountTransactionContext ` and use it in the hint processor when reading the version of a transaction.

---

crates/blockifier/feature_contracts/cairo0/compiled/account_faulty_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/account_without_validations_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/empty_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/security_tests_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/tests/requirements.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1069)

Recompile cairo0 contracts with new compiler + add test to ` get_tx_info ` syscall.

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1073)

Add tests to the use of the query flag in the hint processor when reading the version.

---

crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/transaction/transactions_test.rs

This reverts commit 1223f249e6ad3146a7dd4dbbdf6bdd64069ebd04.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1074)

Revert "Update os resources to match python STARKNET-RC-0.12.3.0. (#1062)"

---

crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1078)

Fix resouce representation

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1047)

Delete write_and_transfer for flexibility

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1048)

Update post-execution tests

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1056)

max_steps returns block bounds if charge_fee is false

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1082)

Combine fields

---

crates/blockifier/src/fee/fee_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1083)

Split function

---

crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1086)

Execution info syscall: update resource bound order

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1087)

Ignore local python venv

---

crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1088)

Set charge_fee=true in PyValidator.execute

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml

Otherwise crates.io won't see it when publishing blockifier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1091)

Move `genco` hack to blockifier crate

---

crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1084)

Post execution checks with auditor struct

---

crates/blockifier/src/fee/actual_cost.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1085)

Remove redundant logic and max_fee() call

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1041)

Move pre-validation checks into method.

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1105)

Missing L1 gas bounds should return Err, not panic

---

crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1107)

Remove STRK price sampling config

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1043)

Added non strict nonce option.

---

crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1104)

Take enforce_fee into account in post-execution
