starkware-libs/blockifier

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/state/papyrus_state.rs
crates/blockifier/src/state/papyrus_state_test.rs

- move to correct location
- fix imports
- use `get_selector_from_name` instead of deprecated const.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/225)

Fix `papyrus_state_test` after merge conflict

---

crates/native_blockifier/build_wheels.sh

- added centos-release-scl and llvm-toolset to manylinux docker, for clang > 3.9 support.
When `blockifier` is added as a dep (which will happen soon),
one of the dependencies requires this clang dependency.
- Ditto for openssel-devel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/258)

Fix build script for native extension

---

crates/blockifier/src/lib.rs

Temporary change.
Currently native_extension needs `DictStateReader`, but it should require `State`. Until that's fixed, we remove the testing feature from test_utils, because we don't want to compile the extension in release mode, but with a `Testing` feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/281)

Remove testing feature from test_utils

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_transaction.rs

- The broken branch was caused by a divergence of versions between blockifier and native_blockifier, will be fixed soon.
- The import we need from blockifier is no longer behind a testing feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/282)

Remove broken py_tx branch and fix dependency

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/build.sh
scripts/build.sh
scripts/build_wheels.sh

Taking by git creates divergence of versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/283)

Grab blockifier by path instead of by git

---

crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_utils.rs
crates/native_blockifier/src/storage.rs

Motivation: block hashes are needed for comparisons between blocks into Python DB vs Rust DB.
Block hashes are currently set as the block ids of the Python blocks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/286)

Create `BlockHeader` when appending state diff

---

Cargo.lock
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs

- Change the `Program` `builtin` field to type `Vec<&'static str>` (extract it using the `BuiltinName` enum) [#841](https://github.com/lambdaclass/cairo-rs/pull/841/files).
- Remove references to Relocatable [#850](https://github.com/lambdaclass/cairo-rs/pull/850/files)
- Change the hash to be named pedersen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/288)

Fix code after cargo update (changes done by LC).

---

crates/native_blockifier/setup.py

This tag is used when deploying to pypi, and should be marked as a 0.X version, given its current state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/318)

Change native-blockifier version

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscall_handling.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs

- Import cairo_rs's `ExecutionResources` as `VmExecutionResources`.
- Rename `ExecutionResourcesManager` -> `ExecutionResources`
- Rename `resources_manager` fields into `execution_resources`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/334)

Renaming `ExecutionResources`

---

crates/native_blockifier/setup.py
crates/native_blockifier/src/py_transaction.rs

Previously, transactions were committed onto the state if they succeeded, which is incorrect in cases where the transaction weight is too big.
Now accepting a python callback, which is given the `tx_weights` and raises an exception if they cannot be added.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/343)

Don't commit transactions before checking if they can be added

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

Since Blockifier is a Lib crate, it suffices to put log statements where necessary, and let the binary user decide on log levels and configs.
In our case, the current user is the Python client, and the above decisions are delegated to it via `Pyo3-log`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/324)

Add logging

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/fee/eth_gas_constants.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs

Whenever we refer to amounts - use `usize`.  `u64` should be used for ids - or if rust enforces us to use it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/376)

Change `u64` to `usize`.

---

crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

Creating two `Storage` instances is risky, because `papyrus_storage` panics if two storages open in the same location.
The idea is that the `Storage` should be initialized using a context-manager in Python when initializing the Batcher, thus guaranteeing only one instance, which is freed on `finally` using `close()` --- this explicit drop appears necessary, since Rust can't seem to track when the instance is dropped in Python, thus not triggering the drop in Rust.
By setting the fields as None, this guarantees a drop in Rust.
The above has the added benefit of not having to verify alignment, since the execution flow guarantees that the (unique!) `Storage` instance is aligned before it is sent to the executor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

Consolidate Storage Access in `native_blockifier`.

---

Cargo.lock
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/papyrus_state.rs
crates/blockifier/src/state/papyrus_state_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/storage.rs

Main changes:
- Fields changed in SN API `StateDiff` (previously `declared_classes` now appear in `deprecated_declared_classes`; rest new fields are currently unused).
- `DeclareTransaction` is now an enum; `InvokeTransaction` changed to `InvokeTransactionV1`.
- Many location changes in SN API (especially to `deprecated_contract_class.rs`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/384)

Bump Papyrus storage to `1d791aa`; SN API to `783885b`.

---

Cargo.toml
crates/blockifier/Cargo.toml
crates/native_blockifier/Cargo.toml

Prevents having to manually sync between blockifier and native-blockifier deps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/392)

Lock dependencies at workspace level

---

crates/native_blockifier/Cargo.toml
rustfmt.toml

No real reason for it to be 2018 (blockifier is already 2021).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/394)

Bump rust edition in native-blockifier

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

- Since we're using `map_err` anyway as part of our logic, making a transparent error doesn't benefit really. 
Most of the change is just moving the error message from the singleton error structs into the big struct.
- Fixes a duplication in the way errors are display, for example `ContractConstructorExecutionError<ContractConstructorExecutionError<...>>`
- Small refactor for returning `Result<Option<call_info>>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/414)

Remove duplicated error structs

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

`validate_call_info` and `execute_call_info` were inverted in the calls to `calculate_tx_resources`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/431)

Fix order of parameters calculate_tx_resources

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/papyrus_state.rs

- Will be used in declare version 2: will be use to check that we have not already declared the given class. And if we did not declare it, we will add (using `set`) the relevant mapping.
- Should return `0` in declare version`<2`.
- Will be used in `get_compiled_class_by_class_hash(class_hash)-> CompiledClass` (which is used in deploy and in execute entry point (to initialize the runner)). Reason: given the `class_hash` we need to extract the `compiled_class_hash` and then we can get the compiled class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/433)

Add `get\set_compiled_class_hash`.

---

crates/blockifier/src/transaction/transaction_execution.rs

Needed for upcoming `beanchmark` module, which gets a json string representing a list of SN API blocks, and simulates its txs in `Blockifier`.
This requires converting the txs to the `Blockifier` type.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/440)

Add a cast from a SN API `Transaction` into `Blockifier` one

---

crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/py_transaction.rs

No reason for the generic, it should always be Read-Only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/454)

Hardcode `MODE = RO` in papyrus reader

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/py_utils.rs

- Use `ThinStateDiff` (no need to maintain a mapping containing the contract classes)
- Add declared classes (cairo1) to `PyStateDiff`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/443)

Add declared classes to StateDiff.

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/py_test_utils.rs
crates/native_blockifier/src/py_transaction.rs

Currently unused, so hardcoded ContractClassV0 everywhere.
This will change soon when we add support for `CasmContractClass`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/456)

Add `CasmContractClass` - initial

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

The `ContractClass` inside `AccountTransaction` is now `Arc`ed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/467)

Remove clippy warning

---

crates/blockifier/feature_contracts/cairo0/compiled/account_faulty_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/account_without_validations_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/empty_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/security_tests_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/tests/requirements.txt

Fixing the version is to prevent frequent CI failures. Nothing special about this version, make sure to update this as needed when new versions come up.
Note: Without this locked version, the CI automatically takes the latest version, which means this test would crash after every cairo release without the lock.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/484)

Fix feature tests and lock cairo version for it

---

crates/blockifier/tests/feature_contracts_compatibility_test.rs

Now running `FIX_FEATURE_TEST=1 cargo test -- --ignored` will fix the test, instead of manually changing the test `fix` variable.
This instruction is now also printed whenever the test fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/485)

Make it easier to fix the feature test

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

Recently, `From<u128> for StarkFelt` was implemented, so no need to cast u128 integers (`Fee` is `Fee(pub u128)`) to u64 before constructing a felt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/500)

Convert u64->u128, and not u128->u64

---

crates/native_blockifier/src/papyrus_state.rs

* Still unused, but will be used soon.
* Implementation is exactly like it is in the `impl` of `PapyrusStateReader`, only using the `state_reader()` getter in order to get the reader (since `PapyrusReader` has another level of indirection due to it saving both the state and contracts reader)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/509)

Finish implementing `StateReader` for `PapyrusReader`

---

crates/blockifier/src/execution/entry_point.rs
crates/native_blockifier/src/py_transaction.rs

- `get_executed_class_hashes` hit infinite recursion.
- Remove `todo!` from python cast, it panics in Python tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/512)

Fix compiled class hash retrieval

---

crates/native_blockifier/src/storage.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/513)

Missing `deprecated_declared_class_hash_to_class` in `append_block` def

---

crates/blockifier/src/execution/entry_point.rs
crates/native_blockifier/src/py_transaction.rs

- `get_executed_class_hashes` hit infinite recursion.
- Remove `todo!` from python cast, it panics in Python tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/521)

Cherry-pick: Fix compiled class hash retrieval (#512)

---

.github/workflows/ci.yml

Currently PRs to main-v0.12.0 don't run CI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/532)

Run CI in PRs for main-v* type branches

---

crates/native_blockifier/src/papyrus_state.rs

Currently unused, will replace the impl on `PapyrusStateReader` soon. The impl is copy-pasted from `PapyrusStateReader`, with the following differences:
* `get_compiled_contract_class` also looks for V1 contract classes, before looking for V0 ones.
* getter for the state_reader now uses the getter method (since the reader is now a field inside PapyrusReader)
Too see exact diff, compare with https://reviewable.io/reviews/starkware-libs/blockifier/455#, which is almost the same (changes are after addressing comments there)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/508)

Start implementing `StateReader` for `PapyrusReader`

---

crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/mod.rs

The pointer itself doesn't change so no need to put the pointer as mut.
(Clippy doesn't let me build locally without this change, probably using an old version of clippy on the CI?)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/548)

Remove unnecessary `mut`

---

crates/blockifier/src/abi/abi_utils_test.rs
crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

Initial gas is the amount of gas allocated to the execution on initiation.
Push this value to the stack when preparing the call arguments.
Based on #515.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/545)

Add initial gas to the execution of an entry point.

---

crates/native_blockifier/src/py_transaction.rs

This is done in order to have a convenient `close` function, which deallocates the executor.
Without this, the executor instance isn't deallocated (at least not immediately), which causes READERS_FULL errors from MDBX.
Python version bump: https://github.com/starkware-industries/starkware/pull/30334
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/585)

Wrap `PyTransactionExecutor` in a newtype

---

crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/593)

Add out of gas test.

---

crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction.rs

Was previously added an left unused.
It is similar to the `PapyrusReader` but with added support for cairo1 contracts (and has a casm contract reader).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/603)

Enable Papyrus reader

---

.cargo/config.toml
crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/errors.rs

Currently too many recursions hit stack-overflow panic, we don't want that.
Increasing the stack size to 72MB is required in order to have the same recursion depth as in CPython, 3000.
This is X36 times the 2MB default, is there a better way?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/612)

Limit recursion depth for entrypoint calls

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/627)

Prevent version 0 attack on argent accounts.

---

crates/native_blockifier/src/py_transaction.rs

Move responsibility to caller.
Rationale: finalize isn't guaranteed to be run, which might leave dangling read transactions.
Python side: https://reviewable.io/reviews/starkware-industries/starkware/30472
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/630)

Don't close executor inside finalize

---

crates/blockifier/src/execution/contract_class.rs

(to handle the case of reaching `unreachable!("Deprecated hints do not have a pythonic version.")` when hitting `CoreHintBase::Deprecated`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/642)

Convert hints to string using ` serde_json::to_string ` (as opposed to ` to_string() `).

---

crates/blockifier/src/state/cached_state_test.rs
crates/native_blockifier/src/py_transaction.rs

Use default constructor and rename variables, as a setup for the more general construction and finalization when using global cache.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/654)

Small refactor default constructors

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/py_transaction.rs

* Constructor will be easier to work with in the upcoming global contract cache feature.
* Reorder: CommitmentStateDiff moved down (importance).
* Moved `TransactionalState` closer to its `impl` (it is a typedef but we treat it like a struct).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/653)

Refactor: Add `TransactionalState` constructor

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/648)

Fix: Updates the cache with the initial values of cells that were only accessed via write (affects the fee calculation and the state diff).

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/contract_class.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/transaction/transaction_utils.rs

Use `initialize_function_runner_cairo_1` (which uses `initialize_all_builtins`. It is based on [CairoFunctionRunner](https://github.com/starkware-industries/starkware/blob/2753bc84eb0b98a31f9f27d73d33fc3116c0185f/src/starkware/cairo/common/cairo_function_runner.py#L31)).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/652)

Add ` segment_arena_builtin ` to the program builtins.

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/658)

Use error handling for relocatable addition.

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/651)

Add nonce count and consider it in the modified contracts.

---

crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/604)

Use BlockNumber in GetBlockHashRequest.

---

crates/blockifier/src/lib.rs
crates/blockifier/src/state/cached_state.rs
crates/native_blockifier/src/lib.rs
rustfmt.toml

- `CachedState` doesn't impl Default really (since `S` isn't doesn't necessarily), this only worked probably due to it working with the testing `DictStateReader`, which is its only user, which might have tricked the compiler. This change makes everything explicit.
- Hide test_utils behind `testing` feature.
- Unrelated: apparent typo in rustfmt (maybe due to breaking change on rustfmt?)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/671)

Cleanup in testing and fmt

---

crates/blockifier/src/execution/syscalls/mod.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/673)

Use the remaining gas in deploy syscall (as the initial gas of the constructor entry point.

---

crates/blockifier/src/execution/cairo1_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/675)

Change ` initial_gas ` to be of type ` u64 ` .

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/test_utils.rs
crates/native_blockifier/src/py_transaction_executor.rs

- rename `recursion_depth`->`current_recursion_depth` for clarity.
- Constant for max depth (and stale comment) replaced with value in `BlockContext`.
- Refactor: hoist up papyrus_storage, it should be first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/688)

Make recursion depth configurable

---

crates/native_blockifier/src/py_transaction_executor.rs
crates/native_blockifier/src/py_utils.rs

Upcoming caching changes will also use `ChainId`, and this will prevent future duplication of logic.
Python: https://reviewable.io/reviews/starkware-industries/starkware/30768
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/728)

Extract `ChainId` directly from python

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/storage.rs

- initialize storage using a `StorageConfig` motivation is two-fold: first, `Storage` will soon be internalized into a more general struct (BlockExecutor), so when we initialize it we want to wrap all the storage-relevant arguments up nicely to differentiate from the other arguments it is initialized with; second, there will soon be an additional argument here (chain_id) and three arguments is starting to get verbose.
- Added a testing initializer for Python usage (currently we're doing this in Python, which is wrong cause this is an implementation detail)
python: https://reviewable.io/reviews/starkware-industries/starkware/30775
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Storage cleanup

---

Cargo.lock
Cargo.toml
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/papyrus_state.rs
crates/native_blockifier/src/papyrus_state_test.rs
crates/native_blockifier/src/py_transaction_executor.rs

This commit simplifies handling read-only transactions (RO tx) in the `PapyrusReader` and `py_transaction_executor.py` modules.
The previous design saved an open RO tx in the instance, which led to unnecessary complexity, including the need for a lifetime/ouroboros pattern. This commit modifies the system to open a new RO tx on demand, which is a more efficient and simpler approach.
Key changes:
- The `PapyrusReader` has been refactored to generate the required transactions on demand. This removes the need to store an open RO tx.
- The `py_transaction_executor.py` module has been significantly simplified. The changes primarily involve the removal of the ouroboros pattern, which required certain fields and complex constructor methods.
With the removal of stored RO tx, we can replace the …

Refactor `PapyrusReader` and `py_transaction_executor.py` to remove unnecessary RO tx storage

---

crates/blockifier/src/transaction/account_transactions_test.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_transaction_executor.rs

* For simplicity, all it does at the moment is hold general_config and max_recursion_depth, where the former's definition was moved into `PyBlockExecutor`'s module, since it is its primary owner.
* It is also in charge of initializing the PyTransactionExecutor for Python.
* Make `py_block_context` into a method of `PyGeneralConfig` --- note that PyBlockInfo can be used there instead of PyAny, will do in separate PR to keep the diff small.
* in subsequent PRs it will also be in charge of Storage, and later on hide both storage and transaction executor from Python.
* The change in `account_transactions_test`.rs is an unrelated unnecessary `clone` clippy spotted only now for some reason.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Add `PyBlockExecutor`

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/storage.rs

- Make `Storage` a pure Rust struct, thus making `PyBlockExecutor` the sole pyo3 construct Python has accesss to.
- Also makes memory management easier, since we don't have to track this at Python.
- Basically `PyBlockExecutor` swallowed `BlockifierStorage`, delegate the same API to `Storage`, with the exception of `validate_aligned` which is executed in Rust in the same way as it did in Python.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/779)

Hide `Storage` from Python

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

Check actual fee before committing the execution result. Revert and charge max fee when running out of gas instead of failing due to FeeTransferError and charging nothing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/796)

Refactor run_or_revert.

---

Cargo.lock
Cargo.toml
crates/blockifier/README.md
crates/native_blockifier/Cargo.toml
crates/native_blockifier/README.md

* make native_blockifier depend on `blockifier` with a `path` when
working locally, and with `version` in crates.io (which doesn't
support path deps).
* add READMEs to both crates.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/801)

rc2 versioning fix and READMEs

---

crates/blockifier/src/state/cached_state_test.rs

The global cache update action will be tested in a subsequent PR (it needs some extra changes in pyo3).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/805)

Add global contract cache test for `CachedState`

---

Cargo.lock
Cargo.toml

Some changes made in `1.0.72` break our Python build, will investigate,
for now we don't anything higher than this.
Python: https://reviewable.io/reviews/starkware-industries/starkware/31211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/813)

Lock serde at 1.0.71 for now

---

.github/workflows/coverage.yml

Token isn't required for public repos (see https://github.com/taiki-e/cargo-llvm-cov/), which is why it wasn't added previously.
However, the following posts claims this fixes the upload errors for public repos: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954/3
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/824)

Attempt to fix coverage upload errors

---

crates/blockifier/src/state/cached_state.rs

- Move state cache-updating logic into a method `update_cache`. This will soon be used when we add an additional transactional state type. Consequently, `StateCache` is now public (since `update_cache` is part of the public API).
- Move local and global contract cache into a method `update_contract_class_caches`, for the same reason as the above.
- Code convention fix: move the private method `update_initial_values_of_write_only_access` to the bottom of the `impl` block.
This is why `move_classes_to_global_cache` and `global_class_hash_to_class` appear in the diff, they were hoisted up above `update_initial_values_of_write_only_access`(but were not changed).
Context: getting ready for removing the python callback in `native_blockifier`. 
This will require a different type of …

Refactor cache handling in `CachedState`

---

crates/blockifier/src/state/cached_state.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/transaction_executor.rs

- Removed `enough_room_for_tx`, a Python bouncer callback, allowing PyTransactionExecutionInfo to be allocated in Rust, rather than on the Python heap (so it is no longer of type `Py<PyTransactionExecutionInfo>`, just `PyTransactionExecutionInfo`). Also, now no longer need specialized Python exception handling, since we are no longer running Python code.
- Added new API to block-executor to replace the callback: `commit_tx` and `abort_tx`, which Python calls after getting the results from the bouncer.
- Added `StagedTransactionalState`, which represents a TransactionalState after the transaction has finished executing. Thus, it only holds the results of the exeuction that are subject to be commited to the state, or the set of executed class hashes. There is still a bit of duplication …

Remove python bouncer callback from `native_blockifier`

---

Cargo.lock
Cargo.toml

Serde locked to `1.0.171` in blockifier conflicts with serde version `^1.0.185` set in Scarb, which makes the two packages incompatible.
Closes #842
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/844)

Unlocked serde version

---

crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/transaction_executor.rs

Sets the stage for the upcoming addition of `validate` to the `TransactionExecutor` api.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/859)

Make `charge_fee` optional in `native_blockifier` execution

---

crates/blockifier/src/transaction/account_transaction.rs

`impl Account Transaction` should appear after the struct definition; `ValidateExecuteCallInfo` was in the way.
Moved it down, cause it isn't important enough to be up top. No other changes, just move.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/871)

account_transaction - formatting

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs
crates/native_blockifier/src/py_block_executor.rs

- Store fee token addresses in a dedicated struct `FeeTokenAddresses`.
- Add `HasTransactionVersion` to represent objects that store
`TransactionVersion` (or store fields that store `TransactionVersion`,
and so on). Ideally, we should have a `Versioned` trait in SN API for
this kind of thing, which will be more generic, rather than
specifically a TransactionVersion.
- Changes in tests currently just preserve the current state, once we
add support for the new transactions we'll update the tests to not
hard-code deprecated transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/889)

Make get_fee_token_balance consider transaction version

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs
crates/native_blockifier/src/py_transaction_executor.rs

This ensures that the `CommitmentStateDiff` doesn't contain any write actions that don't change the existing value.
This is a performance optimization, since it saves the state diff consumer from doing this at a later stage, which could be costly.
Python: https://reviewable.io/reviews/starkware-industries/starkware/31816
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/911)

Read all written values when casting from `CachedState` to `CommitmenttStateDiff`

---

crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/890)

Make `run[_non]_revertible` use fee token address according to version

---

crates/blockifier/src/abi/abi_utils.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs

`storage_key` is fetched modulo `L2_ADDRESS_UPPER_BOUND`, which is smaller than the `PatriciaKey` upper bounds. This change ensures that the `try_from` operation for `StorageKey` stays within bounds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/942)

Unwrap `get_storage_var_address`

---

crates/blockifier/src/transaction/account_transactions_test.rs

tests the same scenario as test_internal_invoke_tx_failure in the Python tests
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/971)

Added a test for the scenario when a non deployed user invokes a transaction

---

crates/blockifier/feature_contracts/cairo0/compiled/test_pair_skeleton_compiled.json
crates/blockifier/feature_contracts/cairo0/test_pair_skeleton.cairo
crates/blockifier/src/fee/strk_gas_price/gas_price_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/tests/feature_contracts_compatibility_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/972)

add a basic test pair contract 

---

.github/workflows/ci.yml

Already merged in main at #823.
This is a ci-only change, which reorganizes the required checks on github.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/974)

Cherry-pick: Use stable clippy.

---

crates/native_blockifier/src/py_validator.rs

Currently it only held a placeholder and was not operational.
Python: https://reviewable.io/reviews/starkware-industries/starkware/31652
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/980)

    Make `PyValidator` use `PyStateReader`

---

crates/blockifier/src/fee.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/transaction/account_transaction.rs

New module is a wrapper around `calculate_actual_fee_and_resources`, which was copied as is from `AccountTransaction`, without any changes. This module takes care of all the various optional customizations for the calc, which helps separate the complex setup from the actual calculation.
Added one usage for the new module, 3 more usages coming up in subsequent commits.
After the last usage is added `calculate_actual_fee_and_resources` will be removed from `AccountTransaction` in favor of this module.
Also bundled `actual_{fee,resources}` into dedicated struct, as they are often passed around together.
Added TODO to actually pass the struct instead of unpacking it, but out of scope for this commit.
Motivation: external validation of transaction fee/resources will soon be added and we don't …

Add `ActualCost` and builder for it + one usage

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

Use `ActualCostBuilder` instead, for less boilerplate and easier customization.
Fixes comments from: https://reviewable.io/reviews/starkware-libs/blockifier/996
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1003)

Remove `calculate_actual_fee_and_resources`

---

crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

This should have been added before, since Python needs blockifier to calculate the actual fee in order to validate that there is sufficient fee for the validation call.
fixes comments from: https://reviewable.io/reviews/starkware-libs/blockifier/997
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1004)

Return `actual_fee` from native validation API

---

crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

Make handle_nonce public and call it before validating in
native_blockifier.
Note that this makes the usual assumption that the state of
TransactionExecutor is reset between calls to it's validate/execute API.
Python: https://reviewable.io/reviews/starkware-industries/starkware/31652
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1007)

Fix fee calculation in native blockifier validation

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs

Method is only used once, in a test, and is probably too specific to appear in `AccountTransaction API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1065)

Remove single use testing util

---

crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

Usage:
```rust
create_calldata(
contract_address: <ContractAddress>,
entry_point_name: "some_entry_point_name",
entry_point_args: [
starkfelt_arg_1,
starkfelt_arg_2,
...
]);
```
To be used instead of this pattern:
```rust
calldata: calldata![
*contract_address.0.key(),                      // Contract address.
selector_from_name("some_entry_point_name").0,  // EP selector.
stark_felt!(2_u8),                      	// Calldata length.
stark_felt!(2_u8)                       	// Calldata: arg1.
stark_felt!(3_u8)                       	// Calldata: arg2.
]
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1066)

Add calldata generator + one usage

---

crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/native_blockifier/src/transaction_executor.rs

- Calculate l1 actual fee via `ActualCost`: its logic was almost identical to the logic of `calculate_actual_fee_and_resources`.
- Required adding `l1_payload_size` which was always None for `AccountTransaction`, which were the only txs `ActualCost` supported thus far.
- Also added `sender_address` for the opposite reason as the prev bullet.
- Removed NEW_TOKEN_SUPPORT TODO since it is already fixed inside `ActualCost`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1039)

Add l1 support to `ActualCost`

---

Cargo.lock
Cargo.toml

Looks like `genco = 0.17.7` from last month breaks compilation. This didn't pop up yet because of our committed Cargo.lock, but since we publish `blockifier` as a lib-crate, it runs an `update` when we publish.
We had to do this on Starknet API here as well: https://github.com/starkware-libs/starknet-api/pull/145
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1089)

Workaround `genco` bug (#145)

---

Cargo.lock
Cargo.toml
crates/native_blockifier/Cargo.toml

- Release includes more functional support for v3 txs, and in particular a new version of SN API.
- Lock `native_blockifier`'s blockifier version to the previous rc to break the circular dependency with papyrus. Similarly, lock SN API to the version that was in the previous rc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1092)

Release 0.4.0-rc3 + bump SN API to 0.6.0-rc0

---

.github/workflows/verify-deps.yml

Based on [this](https://doc.rust-lang.org/nightly/cargo/guide/continuous-integration.html#verifying-latest-dependencies)
recommendation from The Cargo Book.
This will give us a heads-up against a future `genco` problem from one of our deps.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1093)

Add github nightly job that checks that dependencies are not broken

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml

- Includes revert of `Block` changes in the recent release of SN API
- Remove the `genco` hack, they fixed their bug in a new release (0.17.8).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1094)

Release 0.4.0-rc4

---

crates/blockifier/src/execution/syscalls/syscalls_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1071)

Added a test of formatting an error of entry point execution failure.

---

Cargo.lock
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/storage.rs

Added new new storage config options: they now have a separate storage
exclusively for large objects (memory mapped filed).
The config selected ensure (much) more than necessary space per object
(like a very large state diff or contract), and to compensate uses a
small dynamic growth step (if both the growth step and the max size will
be large then each growth step will hang for a bit until the malloc
completes).
Alternatively, the default configuration can be used, but it is a bit
less safe (but is probably fine).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1099)

Reconnect native_blockifier with blockifier and bump papyrus_storage

---

crates/native_blockifier/src/py_validator.rs

- If a DeployAccount has been received but not proccesed yet, we allow a
certain number of txs to skip past initial validations for better user
experience (they'll go through validations during execution later).
- Move pre-validation stage into py_validator method for consistency
with post-validation stage.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1128)

    Add validation skip step due to unprocessed deploy

---

crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_types.rs
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_utils.rs
crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

(Wasn't sure if this should have been split further, since these are all related changes.)
- Remove py_enum_name, it was only used for `tx_type`.
- Push down tx_type extraction into py_tx, it's only used there and is already included inside the `tx` argument.
- Cast string tx_type into `TransactionType` as soon as possible.
- Unify tx parsing logic under `py_tx`
- Rename the arguments py_tx -> tx since `py_tx` shadows the function with the same name.
- Add `From` to `Transaction`, for less verbose initialization.
- Throw regular panic instead of `unimplemented!()` --- this was true in the past when we didn't implement all tx_types, but now that we do any value passed from Python that is not in the match is a bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

Better `TransactionType` handling in `native_blockifier`

---

crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_block_executor_test.rs
crates/native_blockifier/src/test_utils.rs

Specifically, when retrieving block_id from a Papyrus snapshot
it can be a large hash, which we had a bug on back when we assumed it
was a u64.
commit-id:979a9b19

Add Storage mock and test for get_block_id

---

.cargo/config.toml
Cargo.toml
crates/blockifier/Cargo.toml
crates/native_blockifier/Cargo.toml

commit-id:4f026e58
---
**Stack**:
- #1163
- #1162 ⬅

Rust 1.74: move lints to Cargo.toml

---

Cargo.lock
Cargo.toml
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/fee/os_usage_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/utils.rs
crates/blockifier/src/utils_test.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/storage.rs
crates/native_blockifier/src/test_utils.rs
crates/native_blockifier/src/transaction_executor.rs

Fixes #1158.
- Iterating over `Hash{Map,Set}` results in undeterministic behavior,
as the order of iteration is not deterministic. Using `Index{Map,Set}`
ensures deterministic iteration order.
- Add a new rust 1.75 clippy lint that catches this behavior.
Disabled until rust 1.75 is stable (currently 1.74 is stable) in about a month.
Python: https://reviewable.io/reviews/starkware-industries/starkware/32719
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1164)

Don't iterate over HashMap/HashSet

---

crates/blockifier/BUILD
crates/native_blockifier/BUILD
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_validator.rs

- Add `testing` feature to native_blockifier (up until now this feature wasn't available for use in python).
- Compile native_blockifier with the `testing` feature turned on: note that this means that all of blockifier's `create_for_testing` methods will be exposed in production, however in Python that is already the case for the rest of the classes which expose their testing methods.
- Make block_executor/validator testing methods tied to the `testing` feature: this isn't strictly necessary at the moment (since `testing` is default on anyway...), but will become necessary in an upcoming commit which calls a test_utils.rs method, and that one's only available in `any(testing,test)`.
Python: https://reviewable.io/reviews/starkware-industries/starkware/32729
- - -
This change is [<img …

`native_blockifier`: add `testing` feature.

---

Cargo.lock
Cargo.toml
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/fee/os_usage_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/utils.rs
crates/blockifier/src/utils_test.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/storage.rs
crates/native_blockifier/src/test_utils.rs
crates/native_blockifier/src/transaction_executor.rs

This reverts commit 4e1817be67211468fbdef57ed983ab7f30eb83c7.
The change in `native_blockifier` should be made more delicately, looks like Pyo3 has some issues with indexmap>1.9.3 (even though they stated that they support < 3.0.0.
Will reenable soon after sidestepping this issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1184)

Revert "Don't iterate over `HashMap/HashSet` (#1164)"

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/os_usage.rs

Replaces common idiom. Also move getter after `new`, which should be the
first function.
commit-id:026d5d94

Add util `OsResources.resources_for_tx_type`

---

crates/blockifier/src/test_utils/declare.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs

Same idea as `InvokeTxArgs` - will allow easier construction of `DeployAccount` transactions, and soon we will be able to vary over version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1194)

Define and use DeployTxArgs

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1218)

Refactor error unpacking in test_validate_accounts_tx.

---

crates/native_blockifier/src/py_validator.rs

Remove setup/teardown logic: this was relevant for the block executor (which the validator was copied from) due to concurrency limitations of papyrus. But since we are not using papyrus in PyValidator, these are no longer relevant.
In the new flow, multiple `PyValidator` instances can be used concurrently.
GlobalCache is currently not threadsafe, so isn't used in PyValidator. To use it, it must be Mutex'ed and updated from Python after each validate call finishes.
Python: https://reviewable.io/reviews/starkware-industries/starkware/32926
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1221)

native_blockifier: Make PyValidator threadsafe

---

crates/blockifier/feature_contracts/cairo0/compiled/test_contract_compiled.json
crates/blockifier/feature_contracts/cairo0/test_contract.cairo
crates/blockifier/src/transaction/account_transactions_test.rs

Added test _test_count_actual_storage_changes_ in Rust to test the actual number of storage changes for a fee when:
1. Writing a new value to a contract cell
2. Rewriting the same value to the cell
3. Transfering 1 ETH to another account
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1253)

Added test test_count_actual_storage_changes in rust

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_block_executor_test.rs

Tested against: https://github.com/starkware-industries/starkware/tree/arni/blockifier_revert_bug/poc/declare_v2 with a local repo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1295)

Clear global_contract_cache on revert block.

---

crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/transaction/objects.rs

Fix merge failure after an old test was run without rebasing and testing first.
Changes:
a) set_storage_at now returns a result in case of failure to write. This can be unwrapped in test_utils.
b) non_optional_callinfos now returns an iterator, so no need to call into_iter
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1309)

Fix broken merge

---

crates/native_blockifier/src/lib.rs

This allows one to do:
```
import native_blockifier
native_blockifier.blockifier_version()
```
And get the version the native was compiled with.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1249)

native_blockifier: Allow querying for `Blockifier` version.

---

crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1335)

Add MAX_L1_GAS_AMOUNT_U128

---

crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1342)

Change additional as to try_from and try_to

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/test_utils/initial_test_state.rs
crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs
crates/native_blockifier/src/py_block_executor.rs

`BlockInfo` should only contain block-level info, whereas chain-level information should be held at the `BlockContext` level, encapsulated in a dedicated `ChainInfo` struct.
Changes:
Only extract from `BlockInfo` and store in `BlockContext.chain_info: ChainInfo`. All other changes are search-replace + moving the fee_token_address getter into `ChainInfo`.
TODO: extract more stuff from BlockInfo: version-dependant constants should be extracted into a dedicated VersionedConstants, which will be a member of BlockContext
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1324)

Extract from `BlockInfo` into `ChainInfo`

---

crates/blockifier/src/block_context.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/bench/blockifier_bench.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_state_diff.rs

The crux of this commit is the change in `block_context.rs`, which converts `BlockContext` into a wrapper around `BlockInfo` (which used to be `BlockContext`).
Everything else is just delegating the accessors to the internal block_info, made by search-and-replace (no other changes).
Motivation:
- This change the groundwork for future refactor and consolidation of contexts.
- Subsequent commits will extract non block-specific constants from `BlockInfo` into separate `ChainInfo` and `VersionedConstants` structs, which will be siblings of `block_info` inside `BlockContext`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1323)

Make `BlockContext` a newtype around `BlockInfo`

---

crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_state_diff.rs

`PyX` types are intended to represent (a subset) of the real structure of object in Python.
Currently Python is broken do to PyBlockInfo's FromPyObject expecting there to be a `PyGasPrices`, which doesn't exist in Ptyhon
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1353)

fix(native_blockifier): Remove `PyGasPrices`

---

Cargo.lock
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_declare.rs
crates/native_blockifier/src/py_deploy_account.rs
crates/native_blockifier/src/py_invoke_function.rs
crates/native_blockifier/src/py_l1_handler.rs
crates/native_blockifier/src/py_state_diff.rs
crates/native_blockifier/src/py_utils.rs
crates/native_blockifier/src/storage.rs

Less `.0` for very common constructor.
Also added Deref to PyFelt, without any usage at the moment, but will help future refactors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1345)

QOL: Add direct cast from PyFelt into ContractAddress + Deref

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1368)

refactor(state): replace GlobalContractCache default with GlobalContractCache new

---

crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/native_blockifier/src/transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1290)

feat(fee): calculates messages size field

---

crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/utils.rs
crates/native_blockifier/src/py_transaction_execution_info.rs
crates/native_blockifier/src/transaction_executor.rs

Replace PyBouncerInfo's additional_os_resources field to tx_weights field and _calculate_tx_weights in Rust instead of in Python
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1347)

refactor(native_blockifier): pybouncerInfo tx_weights field

---

crates/blockifier/src/transaction/transaction_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1390)

style(fee): fix error handle unpack

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/utils.rs

Modified the tests:
`test_calculate_tx_gas_usage_basic`, `test_invoke_tx`, `test_declare_tx`, `test_deploy_account_tx`, `test_l1_handler`, `test_calculate_tx_gas_usage`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1360)

feat(fee): add linear combination for gas and blob_gas, modify relevant tests

---

crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1400)

refactor: change variable and function names for gas_vector

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

Changes:
1. Implemented get_da_gas_cost, which returns a GasVector (depending on use_kzg_da flag).
2. Deleted calculate_tx_gas_usage_vector, because calculate_tx_l1_gas_usage does the same thing.
3. Derived derive_more::Add for GasVector to easily sum up gas costs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1408)

chore(fee): gas computation refactor

---

crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/objects.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1410)

chore(fee): integer VM gas usage

---

Cargo.lock
crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_types.rs
crates/native_blockifier/Cargo.toml
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1315)

perf(native_blockifier): transaction execution info add serialize

---

crates/blockifier/src/fee/os_resources.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1363)

feat(fee): set the resources slope values

---

crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1407)

feat(execution): add entry_point_syscall_counter

---

crates/blockifier/src/context.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/execution_utils.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/test_utils/prices.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/post_execution_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

- Rename `AccountTransactionContext` into `TransactionInfo`: i want to
use `Context` for something else, and `Account` is a misnomer, since
L1Transactions also generate this instance.
- Create a new `AccountTransactionContext`, which holds `BlockContext`
and `TransactionInfo`: This mirrors `BlockContext`, which holds
`BlockInfo` as well as higher level contexts.
- Remove all unnecessary `get_account_tx` calls.
- Replace all functions that take both `block_context` and `tx_info` with
a single `TransactionContext`.
- Make `EntryPointExecutionContext` hold an `Arc<TransactionContext>`
instead of both a block_context and `tx_info`: previously every entry
point cloned the blockContext and generated a new tx_info, now they
all share the same (identical) one.
Python: …

refactor: make `AccountTransactionContext` hold BlockContext

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/versioned_constants.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_utils.rs
crates/native_blockifier/src/py_validator.rs

- Add gateway constants, these are only for transparency, and aren't used directly by the Blockifier whatsoever.
- Pass `validate_max_n_steps` into the blockifier via native_blockifier, to override versioned constants defaults.
Python: https://reviewable.io/reviews/starkware-industries/starkware/33582
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1369)

feat: add more constants to`VersionedConstants`

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/native_blockifier/src/py_utils.rs

Currently not using them, just adding the deserialization logic and tests.
In upcoming commits this will replace `constants.rs`.
The idea is that values inside `cairo_constants` that are json objects,
that is, have the form:
```json
{
A: x,
B: y,
C: z,
...
}
```
should be parsed as x*A + y*B + z*C + ..., where {x,y,z} must be
integers (otherwise an error is thrown), and where {A,B,C} must
correspond to keys that have already been parsed in the json.
Note: JSON standard doesn't enforce order on the keys, but our
implementation does; we should consider using a format that ensures
order, rather than relying on serde's implementation and `IndexMap`.
For reference, here's the way it looks in the cairo constants flie: https://github.com/starkware-industries/starkware/blob/daaa8ef1e466a1905f88749 …

feat: add Cairo constants to `VersionedConstants` - unused

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/context.rs
crates/blockifier/src/execution/contract_address_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs
crates/native_blockifier/src/py_validator.rs

- Remove from constants module and replace all usages with `VersionedConstants#gas_cost(..)`
- Move all comments from the constants module into the const whitelist in `VersionedConstants`.
- Add gas cost getter to `EntryPointExecutionContext`, for readability
- enclose in closure inside hint_processor.rs for even more brevity.
- Move `Transaction::Initial_gas` into `VersionedConstants`: it is now derived from the constants json.
- No other logic changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1392)

feat(execution): use gas costs only from VersionedConstants

---

crates/blockifier/src/state/cached_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1430)

chore(execution): fix the tests using create_state_changes_for_test for readability and correctness

---

crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_validator.rs
crates/native_blockifier/src/transaction_executor.rs

… PyAny.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1414)

refactor(execution, native_blockifier): make TransactionExecutor.execute() work w/o Py objects

---

crates/blockifier/src/abi/constants.rs
crates/blockifier/src/execution/entry_point.rs
crates/native_blockifier/src/errors.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1415)

feat(execution): moved global max step limit to input validation

---

crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/transaction/account_transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1443)

chore(execution): consume state_changes on state_changes_count from

---

crates/blockifier/src/execution/deprecated_entry_point_execution.rs
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/hint_processor.rs
crates/blockifier/src/execution/entry_point_execution.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1437)

feat(execution): calculate the syscall resources for every entry point

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1440)

chore(fee): update os resources and fix expected

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/transactions_test.rs

Note sure how main got broken this way...
NOTE: one of the changes here is in contract_class.rs, which isn't a test module
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1451)

fix: memory holes tests

---

.cargo/config.toml

It's impossible to build the native blockifier on a mac without those flags.
Import constant only for the necessary feature otherwise compilation fails
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1406)

fix(native_blockifier): fix build for mac + unused import

---

crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_checks.rs
crates/blockifier/src/fee/fee_test.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1399)

feat(fee): add GasVector to TransactionExecutionInfo

---

crates/blockifier/src/test_utils/declare.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transaction_utils.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_declare.rs
crates/native_blockifier/src/py_transaction.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1456)

refactor(transaction): use ClassInfo in Declare transaction

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1467)

feat(execution): round block_number and timestamp for the execution info syscall in validate_mode

---

crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/transactions.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1475)

feat(fee): add gas cost for code bytes

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1458)

feat(fee): add events gas cost

---

crates/blockifier/src/execution/bouncer.rs
crates/native_blockifier/src/py_transaction_execution_info.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1489)

feat(fee): add n_events field to BouncerInfo

---

crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/mod.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/transactions_test.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1490)

refactor: move the event size limit constants into versioned_constants

---

crates/blockifier/feature_contracts/cairo0/account_faulty.cairo
crates/blockifier/feature_contracts/cairo0/compiled/account_faulty_compiled.json
crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1496)

test(execution): get_sequencer_address in test_validate_accounts_tx

---

crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/transactions_test.rs

refactor: replaced default_invoke_tx_args with macro that enforces to explicitly define max_fee
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1510)

refactor: replaced default_invoke_tx_args with macro that enforces to explicitly define max_fee

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/cached_state_test.rs
crates/blockifier/src/state/state_api.rs
crates/blockifier/src/test_utils/dict_state_reader.rs
crates/native_blockifier/src/state_readers/papyrus_state.rs
crates/native_blockifier/src/state_readers/py_state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1325)

fix: state trait does not require &mut self

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/state/state_api.rs

`to_state_diff` pre-supposes two states, one before and one after, to build the difference.
This has no reason to be part of `StateReader` trait, whose only concern is to read the current state. There should be no requirement for the struct implementing it to keep a record of the changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1326)

fix: remove to_state_diff from StateApi

---

Cargo.lock
crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/execution/deprecated_syscalls/mod.rs
crates/blockifier/src/execution/syscalls/hint_processor.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

* Had to bump serde_json due to some apparent bug with the recent stable rust.
* Make 13_1 consts backwards compatible
Assign the following defaults for keys missing in versioned_constants
files (for example, they are missing in versioned_constants_13_0.json).
- EventSizeLimit => max values
- L2ResourceGasCosts => 0 values
- validate rounding numbers => 1 (to preserve past no-rounding
behavior). This required bundling them up in a specialized struct in
order to define a custom default as 1 (rather than 0). 
- Add test for default values: required extracting validation logic of
`OsResources` so it won't trigger automatically in tests.
Python: https://reviewable.io/reviews/starkware-industries/starkware/34004
- - -
This change is [<img src="https://reviewable.io/review_button.svg" …

chore: move validate consts into os constants

---

crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

If os resources' inner tx is missing `constant` and `calldata_factor` keys, then:
- assume it is a flat `ExecutionResources` instance, and put its contents inside a `constant` key.
- initialize calldata_factor as default (all zeros).
Python: https://reviewable.io/reviews/starkware-industries/starkware/34026
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1529)

feat: backwards compatibility for calldata_factor

---

crates/blockifier/resources/versioned_constants_13_0.json

Changes between this and the current versioned_constants:
- no `event_size_limit`
- invoke_tx_max_n_steps is 3_000_000 instead of 4_000_000
- no `l2_resource_gas_costs`
- multiple value changes in os_resources
- `vm_resource_fee_cost` is X2 for all values.
No other changes (in particular, os constants is indeed _unchanged_)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1520)

feat: add versioned_constants_13_0.json

---

crates/blockifier/src/versioned_constants.rs

- validate invocation had a syntax error, which was hidden by the cfg
- remove `testing` from the cfg, since we all compile with `testing` during development, and it's just not what we want.
Python: https://reviewable.io/reviews/starkware-industries/starkware/34038
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1537)

fix: versioned constants validate

---

crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1538)

Elin/merge main v0.13.1 into main

---

crates/blockifier/src/state/errors.rs

Change previous error which prints out as:
```
Class with hash ClassHash(
StarkFelt(
"0x00000000000000000000000000000000000000000000000000000000000004d2",
),
) is not declared.
```
into:
```
Class with hash 0x00000000000000000000000000000000000000000000000000000000000004d2 is not declared.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1563)

refactor: make StateError::UndeclaredClassHash a one-line error

---

crates/blockifier/src/bouncer.rs
crates/blockifier/src/bouncer_test.rs
crates/blockifier/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1444)

refactor: add BlockWeights for the future bouncer

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/resources/versioned_constants.json
crates/blockifier/src/execution/entry_point.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/versioned_constants.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1519)

refactor: remove f64 usage at blockifier

---

crates/blockifier/src/transaction/test_utils.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1606)

test: remove the test util create_account_tx_test_state

---

crates/blockifier/src/execution/deprecated_syscalls/deprecated_syscalls_test.rs
crates/blockifier/src/execution/syscalls/syscalls_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1649)

chore: refactor calldata to use concat

---

crates/blockifier/src/test_utils.rs

Aligned with this example: https://github.com/starkware-libs/blockifier/blob/20a895343ec21b6b2eebee41f4087159df126096/crates/blockifier/src/transaction/transactions_test.rs#L1687-L1696
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1647)

chore: align creation of calldata from vec

---

crates/blockifier/src/blockifier/transaction_executor.rs

The docstring was not updated since is was first created in: #447.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1651)

chore: fix docstring of tx_executor execute

---

crates/blockifier/src/blockifier/transaction_executor.rs
crates/blockifier/src/bouncer.rs
crates/blockifier/src/execution/call_info.rs
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/actual_cost_test.rs
crates/blockifier/src/fee/gas_usage_test.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/objects_test.rs
crates/blockifier/src/transaction/transaction_execution.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1666)

refactor(execution): add messages info to ExecutionSummary

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/execution/entry_point_test.rs
crates/blockifier/src/execution/errors.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1712)

feat: add the new stack trace to ValidateTransactionError

---

crates/blockifier/src/bouncer.rs
crates/blockifier/src/bouncer_test.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/errors.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1644)

refactor(execution): bouncer update function

---

crates/blockifier/src/fee/gas_usage.rs
crates/blockifier/src/fee/gas_usage_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1744)

fix(fee): count events of inner calls in get_tx_events_gas_cost

---

crates/blockifier/src/transaction/transactions_test.rs

chore: use valuse in transactions_test for parametrization
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1789)

chore: use valuse in transactions_test for parametrization

---

crates/blockifier/src/blockifier/block.rs
crates/blockifier/src/context.rs
crates/blockifier/src/test_utils/struct_impls.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1791)

feat(concurrency): add concurrency flag to block info

---

crates/blockifier/src/transaction/test_utils.rs

Make the order of the parameters in the macro match the struct: `InvokeTxArgs` etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1794)

chore: orgenaize tx_args macro to follow order

---

crates/blockifier/src/concurrency/test_utils.rs
crates/blockifier/src/concurrency/versioned_state_proxy.rs
crates/blockifier/src/concurrency/versioned_state_proxy_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1857)

refactor(concurrency): use ` ThreadSafeVersionedState ` in tests and define appropriate methods

---

crates/blockifier/src/concurrency/scheduler.rs
crates/blockifier/src/concurrency/worker_logic.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1916)

chore(concurrency): complete commit_tx - post re-execution, delete writes and invoke revalidate

---

crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1942)

fix: bug - os kzg resources is not zero in old versions

---

crates/blockifier/Cargo.toml
crates/blockifier/bench/blockifier_bench.rs
crates/blockifier/src/blockifier.rs
crates/blockifier/src/blockifier/transfers_flow_test.rs
crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/transfers_generator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1917)

refactor: share benchmark code with simple flow test

---

crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1958)

refactor(concurrency): change worker executor field block context to reference

---

crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/account_transaction.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1965)

refactor(concurrency): use state reader generic, instead of updatable, when possible

---

crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/transaction/execution_flavors_test.rs
crates/blockifier/src/transaction/objects.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1968)

chore: clean fee utils

---

crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1971)

fix: remove unnecessary re-computation of total gas field

---

crates/blockifier/src/concurrency/versioned_state_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1955)

test(concurrency): test scenarios of validate_reads with unvalid reads

---

crates/blockifier/src/concurrency/worker_logic_test.rs
crates/native_blockifier/src/py_block_executor.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1983)

chore(native_blockifier): delete TypedTransactionExecutionInfo

---

crates/blockifier/src/concurrency/worker_logic_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1985)

fix(concurrency): fix usage of invoke_tx_args! macro with redundent field name

---

crates/blockifier/src/concurrency/versioned_state.rs

…reads
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1981)

fix(concurrency): add assert message to the declared_contracts assertion in validate_reads

---

crates/blockifier/src/fee/fee_utils.rs
crates/blockifier/src/transaction/errors.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1986)

fix: balance print in errors

---

crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/context.rs
crates/blockifier/src/state/cached_state.rs
crates/blockifier/src/transaction/account_transaction.rs
crates/blockifier/src/transaction/transaction_execution.rs

too big in concurrency mode
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1980)

fix(concurrency): add the sequencer key when checking if the tx is

---

crates/blockifier/src/concurrency/scheduler.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1989)

fix(concurrency): stop the transaction committer when the scheduler is done

---

crates/blockifier/src/concurrency/scheduler_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1993)

chore(concurrency): fix the test test_finish_validation

---

crates/blockifier/src/blockifier/transaction_executor.rs
crates/blockifier/src/concurrency/versioned_state.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1988)

refactor(concurrency): use visited_pcs in execute_chunk

---

crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs
crates/native_blockifier/src/lib.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_objects.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1992)

feat: added private versioned constants

---

crates/blockifier/src/abi/sierra_types.rs
crates/blockifier/src/concurrency/flow_test.rs
crates/blockifier/src/concurrency/scheduler.rs
crates/blockifier/src/concurrency/scheduler_test.rs
crates/blockifier/src/concurrency/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1830)

test(concurrency): multithreaded flow test for the scheduler

---

crates/blockifier/src/concurrency/flow_test.rs
crates/blockifier/src/concurrency/scheduler.rs
crates/blockifier/src/concurrency/scheduler_test.rs
crates/blockifier/src/concurrency/worker_logic.rs
crates/blockifier/src/concurrency/worker_logic_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/1991)

chore(concurrency): sleep if there are no tasks

---

crates/blockifier/src/test_utils/contracts.rs

This is useful for tests with parameterized version.
Also moved private functions to appear after public ones, *no logic changes there*.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2002)

chore: make FeatureContract::cairo_version public

---

crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2064)

fix(transaction): change deploy_account default version to be V3

---

crates/blockifier/src/state.rs
crates/blockifier/src/state/error_format_test.rs
crates/blockifier/src/state/errors.rs

change error format to hex
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2053)

fix: state error undeclared class hash format

---

crates/blockifier/src/concurrency/fee_utils_test.rs
crates/blockifier/src/concurrency/versioned_state_test.rs
crates/blockifier/src/concurrency/worker_logic_test.rs
crates/blockifier/src/state.rs
crates/blockifier/src/state/error_format_test.rs
crates/blockifier/src/state/errors.rs
crates/blockifier/src/test_utils/declare.rs
crates/blockifier/src/test_utils/deploy_account.rs
crates/blockifier/src/transaction/account_transactions_test.rs
crates/blockifier/src/transaction/transactions_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2075)

Dori/Merge main-v0.13.2 into main

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/test_utils/contracts.rs

This is useful for aggregator objects that want to keep track (via hashmap) of the number of contracts initialized inside a test.
In particular, a soon-to-be-added TransactionGenerator object will use this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2077)

feat: add Hash,[Partial]Eq to test utils

---

crates/blockifier/src/test_utils.rs
crates/blockifier/src/transaction.rs
crates/blockifier/src/transaction/error_format_test.rs
crates/blockifier/src/transaction/errors.rs

**Stack**:
- #2078
- #2073
- #2072
- #2069
- #2082 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2082)

fix: contract class version mismatch format

---

crates/blockifier/src/transaction/error_format_test.rs
crates/blockifier/src/transaction/errors.rs

**Stack**:
- #2078
- #2073
- #2072
- #2069 ⬅
- #2082
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2069)

fix: declare transaction error format

---

crates/blockifier/src/execution/entry_point_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2087)

test: test segment arena number of instances

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2049)

feat: expose versioned constants from past versions

---

Cargo.lock
Cargo.toml
crates/blockifier/Cargo.toml
crates/blockifier/src/test_utils/struct_impls.rs
crates/blockifier/src/versioned_constants.rs
crates/blockifier/src/versioned_constants_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2100)

Tzahi/Merge main-v0.13.2 into main

---

Cargo.toml
crates/blockifier/src/fee/actual_cost.rs
crates/blockifier/src/state/cached_state_test.rs
crates/native_blockifier/src/py_block_executor.rs
crates/native_blockifier/src/py_utils.rs
crates/native_blockifier/src/py_validator.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/blockifier/2110)

feat(native_blockifier): allow overriding max invoke steps
